### ISSUE TITLE
Rebranding the project

### ISSUE THREAD

**Issue by akien-mga** [LibreSprite/LibreSprite#10]
See #8 for the issue where you can propose new names for the project.

This issue is meant to discuss the technical stuff that will have to be done to properly rebrand the project. I'll make this a list of checkboxes, feel free to add new stuff in comments and I can edit the OP.

---

Things to do:
- [x] Rename the repo (and potentially the GitHub organisation)
- [x] Edit the README.md (and all other doc text files) to remove direct redirections to the @aseprite repo (reporting issues, etc.)
  - [x] Add a section about the fork's purpose/history and link to the original project for attribution (and fair-play :))
- [x] Rename (and edit) files containing `aseprite` in their name, e.g. `desktop/aseprite.desktop`. [partly done]
- [x] Adjust license headers to keep credit for the original author, and add name and credit for the new project for 2016 onward.
- [x] If wanted, ask GH staff to decouple the new repo from the original one (so that it's not always marked as "forked from aseprite/aseprite", which makes it a kind of sub-repo in GitHub)
- Likely other things, did not look to deep yet.

What we should avoid doing:
- Renaming stuff (methods, variables) in the source code that would contain `aseprite`. In a first time it would likely not add any value, and just make it more difficult to compare the two projects if the original one ever decided to go back to a GPLv2-compatible license.
- Removing credits (that's not something to avoid, that's a _no go_!)

**Comment by dacap** [comment]
Hi @akien-mga, I've just saw this issue, about this specific point:

> If wanted, ask GH staff to decouple the new repo from the original one (so that it's not always marked as "forked from aseprite/aseprite", which makes it a kind of sub-repo in GitHub)

Are you trying to misleading users to make them think that I'm the one that is using your source code instead of the other way around? I hope this isn't the case. Remember that you are using my work. You *are* a fork of my code.

**Comment by akien-mga** [comment]
>> If wanted, ask GH staff to decouple the new repo from the original one (so that it's not always marked as "forked from aseprite/aseprite", which makes it a kind of sub-repo in GitHub)

> Are you trying to misleading users to make them think that I'm the one that is using your source code instead of the other way around? I hope this isn't the case. Remember that you are using my work. You are a fork of my code.

GitHub "forks" and project forks are two different things. GitHub using the concept of "forks" for the purpose of its pull request workflow. GitHub forks are lesser repos which have less features than "non-fork" repos, and all forks of a given "main" repo are actually part of this initial repo. If we make commit in this repo, they are also part of your repo, and vice versa.

For example, any branch with new commits on this repo would show a link to propose to merge our changes in your original repo, as we are registered as a "functional" fork for GitHub.

So if we do a real project fork, and not just a functional copy for the sake of making pull requests to your repo, then separating the two repos as far as GitHub is concerned would be desirable, so that the two repos can live their own life without impacting each other. GitHub changed the meaning of the heavy "forking" notion to a kind of "positive social forking". In our case, we're clearly on the former meaning, and thus GitHub's semantics don't match our use case.

Also, about your implication that I would be trying to mislead users into whatever... That's just paranoid.
See initial post:

> Add a section about the fork's purpose/history and link to the original project for attribution (and fair-play :))

I'd even go as to say that we'd make it very clear that there is still a commercial version being developed and that people are encouraged to buy it if they are more interested in extended support and newer features than open source code. But if you want to go all paranoid and start accusing us of trying to mislead users and steal your work, well... we might just keep it to the license's terms (i.e. give attribution and keep developments GPLv2-compatible).

**Comment by dacap** [comment]
> GitHub forks are lesser repos which have less features than "non-fork" repos, and all forks of a given "main" repo are actually part of this initial repo.

It makes sense from a functional standpoint. I think that if that is beneficial for both projects so you can go ahead.

**Comment by Wuzzy2** [comment]
Fully agree, this should be rebranded, otherwise the confusion is just too high.
Mentioning that this is a fork of Aseprite makes sense, simply for historic interest. But it should be made clear that the original Aseprite is proprietary software and its author denies its users essential freedoms. Users should also not be *encouraged* to use Aseprite.

Simply put, Aseprise can be *mentioned* but should not be *advertised*. I don't believe the goal of this project is to be merely a “demo version” and advertisement for Aseprite, this just doesn't seem right.

The reason for this is that advertising Aseprite would be advertising proprietary software, which would go aganst the goal of spreading free software.

I also like to make clear that even in the GPLed Aseprite, you are still required to at credit the original authors, but I think this should be obvious.

**Comment by akien-mga** [comment]
Went ahead with the rebranding to **LibreSprite** as discussed in #8. The README and other documentation was edited, and the CMake project and binary were renamed to "libresprite".

There would still be a lot left to do to fully rebrand the project, but I think I'll stop here for now. Any more work should be done by people who actually intend to maintain this fork, and so far I haven't seen any clear candidate (#1).

**Comment by Zughy** [comment]
3 tasks weren't unchecked but they were actually completed. Project is rebranded, contributors are told to edit headers in the PR template and LibreSprite doesn't result as an Aseprite fork since a long time. Closing
