### ISSUE TITLE
Any progress on the Mac build of LibreSprite?

### ISSUE THREAD

**Issue by ItsCbass** [LibreSprite/LibreSprite#100]
Hello! I'm a MacOS-based developer and have been looking for a nice pixel-art program. I stumbled upon LibreSprite and was super excited to see that it was like Aesprite but free. However, I noticed that there is no MacOS build available to download and I wanted to ask yall if there has been any progress on getting a build?

Thanks,
YourLocalCbass

**Comment by maujin111** [comment]
Not much actually, I was trying to compile it with several skia versions but I have failed in my attempts but a MacOs release is one of our priorities, so we will keep working on it

**Comment by YourLocalCbass** [comment]
Thank you for continuing to work on it, I can't wait to start using it!

**Comment by Zughy** [comment]
Closing in favour of #76
