### ISSUE TITLE
Old port, Old fatal bugs, Libresprite instant Crash

### ISSUE THREAD

**Issue by BunnyUsagi** [LibreSprite/LibreSprite#106]
i was trying all day to install aseprite, then i realized that this is basically a port, but it comes with a bug i don't know how to fix, i tried installing a theme (than) and saved, restarted the app, except that now instantly crashes, no matter what i do, even after re-installing or deleting any file i find related to the program it keeps crashing... this happens on older versions of aseprite but it's fixed after an update, but since there isn't a newer version of librespite the bug remains and the app doesn't want to start, is there some path i have to check or files i don't know that i have to delete in order for libresprite to function again?

**Comment by maujin111** [comment]
When you have to delete the folder "C:\Users\AppData\Roaming\libresprite" see #55.
This is not an old port, this is an old version that is being updated as much as we can.

**Comment by maujin111** [comment]
@BunnyUsagi  You have to delete the folder "C:\Users\AppData\Roaming\libresprite" see #55. You have to make sure that the theme you use is for aseprite o libresprite v1
This is not an old port, this is an old version that is being updated as much as we can.
