### ISSUE TITLE
gui.xml is not working

### ISSUE THREAD

**Issue by Salem-McKoi** [LibreSprite/LibreSprite#107]
I downloaded LibreSprite today, but every time I try to open it I get the same error? It just shows a window that states "gui.xml is not working"

**Comment by Zughy** [comment]
Hello @Salem-McKoi , can you tell us more about the issue?
Like, what's your OS, what version are you running, if you're using custom themes

**Comment by maujin111** [comment]
Please provide more information, i will close this issue now but i will re open it if is necessary
