### ISSUE TITLE
Overscaled screen

### ISSUE THREAD

**Issue by RetroNuva10** [LibreSprite/LibreSprite#108]
Was messing with the view scaling options to attempt to fix this issue https://github.com/LibreSprite/LibreSprite/issues/33, and quit the program with the scale of a standard-ish scale, but after re-opening the program I was greeted to an oversized editor with no apparent way of fixing it. I tried reinstalling and installing it again, but it hasn't changed:
![image](https://user-images.githubusercontent.com/61289806/114249146-c0303c80-9967-11eb-84e3-fcb833d06303.png)

**Comment by maujin111** [comment]
Have you tried deleting the folder on " C:\Users\User\AppData\Roaming\LibreSprite "
