### ISSUE TITLE
Menu Help > Tutorial sends to a page who doesn't exists

### ISSUE THREAD

**Issue by iddhbaptista** [LibreSprite/LibreSprite#110]
![image](https://user-images.githubusercontent.com/79605934/116545059-505a0580-a8c6-11eb-8f34-4593e7760103.png)

These menu item opens this [link](https://github.com/LibreSprite/LibreSprite/tutorial/), who doesn't exists.

**Comment by maujin111** [comment]
Currently working on it

**Comment by Zughy** [comment]
Closing in favour of #120 which is more complete
