### ISSUE TITLE
Wiki return 403 code

### ISSUE THREAD

**Issue by idriss-code** [LibreSprite/LibreSprite#111]
I search compiling information but the wiki return a 403 code.

**Comment by Anno2003** [comment]
Any updates on this? I would also like to see the wiki, but it's still returns a 403 code.

**Comment by brickviking** [comment]
A very rough guide for Linux users (and possibly MacOS terminal) here:
~       $ cd ~/src # Make this if you haven't already.
~/src $ git clone https://github.com/LibreSprite/LibreSprite
...
~/src $ cd LibreSprite && git submodule update --init --recursive
...
~/src/LibreSprite $ mkdir build && cd build && cmake ../
............... lots of output ............

The rest you should be able to figure out, though you will have to have the required libraries and headers already installed. CMake will generally tell you what those are if it doesn't find them.

I hope this helps in the interim. I can't really give instructions for any version of Windows as I don't use it much.

**Comment by MintStudios** [comment]
If you actually look in the version history, you'll find an INSTALL.MD. @PerryHugh we should probably put that file back in the repo.

**Comment by RobLoach** [comment]
May be easier to use the Wiki provided by GitHub?
