### ISSUE TITLE
CREATORS OF LIBRESPRITE, PLEASE ADD ASEPRITE 1.3 FEATURES, PLEASE?

### ISSUE THREAD

**Issue by cgaldieri** [LibreSprite/LibreSprite#115]
all the features showcase:
https://youtu.be/4emFL4aV9WM

**Comment by cgaldieri** [comment]
I KNOW THAT THIS IS NOT IMPORTANT!!!!!!

**Comment by maujin111** [comment]
Those are fantastic features, maybe in the future.  We are now working to fix the know bugs but, stay tuned to the project.

**Comment by cgaldieri** [comment]
ok
