### ISSUE TITLE
Wiki returns error 403

### ISSUE THREAD

**Issue by maska228** [LibreSprite/LibreSprite#118]
![image](https://user-images.githubusercontent.com/67519438/120068820-e8f1ca00-c0ac-11eb-9b79-7ce64e06f004.png)

![image](https://user-images.githubusercontent.com/67519438/120068812-d8d9ea80-c0ac-11eb-8f26-1e51ef514403.png)

**Comment by maujin111** [comment]
Duplicate of #111 Currently working on it

**Comment by Zughy** [comment]
(close it?)
