### ISSUE TITLE
Invalid Help Links

### ISSUE THREAD

**Issue by Claeb101** [LibreSprite/LibreSprite#120]
Links for donation, about, documentation, tutorial, etc. under the "help" menu in LibreSprite do not link to a proper github page. Instead, this results in a GitHub PageNotFound. The issue seems to be a simple mistake of not accounting for the "/tree/master/" part of the path when referencing a folder in the repository using GitHub.

**Comment by Claeb101** [comment]
I would be happy to work on this if needed!

**Comment by maujin111** [comment]
@Claeb101 if you can do it, it would be great
