### ISSUE TITLE
Lagging and low fps in libreSprite

### ISSUE THREAD

**Issue by ParmesanPiraten** [LibreSprite/LibreSprite#121]
LibreSprite used to work fine for me but one day it just started lagging like crazy. It only happens when I'm holding certain tools such as the normal paintbrush. Essentially I can't move my mouse without the courser slowly lagging its way around. This can be avoided by zooming in to the point where you can't even see the entire canvas. The fps issue gets fixed but there's no way I could work like that. Any help and suggestions would be heavily appreciated. Also, I'm not a person on the technical side so try and write using understandable English unless you really need to.

**Comment by JunkMeal** [comment]
Just installed it and lags with low fps on linux

**Comment by maujin111** [comment]
Implementing a new backend will solve this issue #2
