### ISSUE TITLE
Forum Spam > Use GitHub Discussions?

### ISSUE THREAD

**Issue by RobLoach** [LibreSprite/LibreSprite#124]
The [LibreSprite Forum](http://www.libresprite.org/forums/) is getting a lot of spam. May be easier to make use of the [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) instead?

**Comment by Zughy** [comment]
It now results dead

**Comment by Zughy** [comment]
As there are [Discord](https://discord.gg/95gbyU5) and [Matrix](https://matrix.to/#/#libresprite-talk:matrix.org) already, I personally think these two are enough and that there is no need to create another space where to chit-chat. If any core dev agrees, please close this issue
