### ISSUE TITLE
Matrix alongside Discord

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#127]
I've been suggested to join LibreSprite Discord here => https://github.com/LibreSprite/LibreSprite/pull/103#issuecomment-882915315, which I find kind of a paradox for a FOSS project born because of the original one switched to a proprietary license. I understand Discord is way more known between people, but it'd be nice to have an official [Matrix](https://matrix.org/) room, bridged with Discord via https://t2bot.io/discord/. In this way, people (like me) can have a FOSS alternative to take part to the community, without being forced to use a proprietary software

**Comment by maujin111** [comment]
There is already a room on matrix https://matrix.to/#/#freenode_#libresprite:matrix.org that you can join

**Comment by Zughy** [comment]
Yes, that's what I did a couple of days ago. But it's apparently dead (not even you are considering it, even if I've tagged you). What I'm proposing here is to have an official Matrix space, bridged with a couple rooms on Discord. Also, there are no pixel art communities on Matrix yet, so it'd mean to kill two birds with one stone. In this way everyone is happy: FOSS enthusiasts like me who'd like to stick on a FOSS solution, and people who don't bother that much.

I saw, through a friend of mine, that you have a lot of people on Discord. I'm pretty sure (or at least I hope so haha) that someone wouldn't mind administrate the Matrix side. I'd step up myself, but I already have a lot of things to manage.

On the contrary, and completely unrelated, if you need someone to put things in order here on GitHub (talking about issues), I'd be glad to help

**Comment by maujin111** [comment]
Here is the link to the two rooms join https://matrix.to/#/#libresprite-talk:matrix.org
