### ISSUE TITLE
Some libraries not found automatically when compiling

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#137]
It happens since https://github.com/LibreSprite/LibreSprite/commit/6fa5a521f1be532122ef3b1ef44216d7188d5c79. @PerryHugh 
I have zlib1g installed (dev and not)

![imagen](https://user-images.githubusercontent.com/63455151/128616528-b30bcfaa-83bd-42f5-962a-62baf9984f20.png)

**Comment by maujin111** [comment]
> It happens since [6fa5a52](https://github.com/LibreSprite/LibreSprite/commit/6fa5a521f1be532122ef3b1ef44216d7188d5c79). @PerryHugh
> I have zlib1g installed (dev and not)
> 
> ![imagen](https://user-images.githubusercontent.com/63455151/128616528-b30bcfaa-83bd-42f5-962a-62baf9984f20.png)

Could you please try with the beta1.2 branch?

**Comment by nanoslayer** [comment]
Not sure what the problem is here. Which platform are you building on? It seems like you are using Ubuntu. Are you sure zlib1g-dev is installed? Can you remove the build directory and try again?

Building on Ubuntu seems to work in [my tests](https://builds.sr.ht/~adnano/job/561917). See the [build manifest](https://builds.sr.ht/api/jobs/561917/manifest) for the list of packages that you need to install.

**Comment by maujin111** [comment]
@nanoslayer Yesterday before the merge I was able to compile it, and now I can not compile. It gives me the same error. I'm using Ubuntu 20.04

**Comment by Zughy** [comment]
@nanoslayer I went more radical recloning everything and yes, the zlib problem has disappeared indeed. But now I'm stuck at the same screen of Maujin

![imagen](https://user-images.githubusercontent.com/63455151/128631150-f633d9f6-0866-4dcd-b816-dfaaccd92210.png)

**Comment by maujin111** [comment]
then you do "sudo apt-get install libpng-dev"
![Captura de pantalla de 2021-08-08 07-01-35](https://user-images.githubusercontent.com/25780951/128631281-396d9794-2dca-45ee-baf9-0d8abbede986.png)
and then "sudo apt-get install cmake libfreetype6-dev libfontconfig1-dev xclip"
![Captura de pantalla de 2021-08-08 05-39-16](https://user-images.githubusercontent.com/25780951/128631372-408814d7-7603-44bb-a644-4d981977b82b.png)
and then "sudo apt-get install libgif-dev"
![Captura de pantalla de 2021-08-08 07-06-28](https://user-images.githubusercontent.com/25780951/128631412-907394b4-3f62-4d19-9261-5c7ff1c36302.png)
and it keep going like that, now I'm stuck

**Comment by nanoslayer** [comment]
These are the packages that you need to install on Ubuntu:

- gcc
- cmake
- ninja-build
- libfreetype6-dev
- libgif-dev
- libgtest-dev
- libjpeg-dev
- libpixman-1-dev
- libpng-dev
- libtinyxml-dev
- libx11-dev
- libxcursor-dev
- zlib1g-dev

Specifically, the last screenshot is indicating that libpixman-1-dev is missing.

Once you have installed all of those, can you remove the build directory and try again?

**Comment by Zughy** [comment]
Damn, you were faster than me by about 30 seconds.
The point is, this is not indicated anywhere, the install.md file should be updated then, to declare this one fixed
