### ISSUE TITLE
Should we edit the preamble of code files?

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#144]
Right now almost every code file starts with
```
// Aseprite
// Copyright (C) 2001-201x David Capello
```
where `x` goes from 0 to 6

but this isn't solely David Capello code anymore. So I was wondering if doing somehting like this could be ok

```
// Aseprite - Copyright (C) 2001-201x  David Capello
// Libresprite - Copyright (C) 201y LibreSprite
```
where `y` is the year when that code file was changed for the first time (for instance, Minetest doesn't specify the year of the latest commit).
Tagging @JeromeMartinez as he seemed to me he knew a lot about licenses and copyright, when Aseprite went proprietary

**Comment by maujin111** [comment]
I agree this should be a new standard on the code

**Comment by Zughy** [comment]
Thinking more about it, a cleaner implementation would be to simply put
`// LibreSprite - Copyright (C) 2016 LibreSprite`
instead of putting a different year according to when it was edited the first time. Because, well, it was forked in 2016, and it also means avoiding any possible confusion/delay with contributors that 90% of the time would forget to edit those lines

**Comment by jjhaggar** [comment]
I'm not sure if I'd feel comfortable with removing the mention of the "father" of LibreSprite and its "older brother". I think that having both lines is a nice thing to do, and also clean and clear enough. 

Something like this:
// Aseprite - Copyright (C) 2001-2016  David Capello
// Libresprite - Copyright (C) 2018 LibreSprite

The date of the change of license was 2016:
![image](https://user-images.githubusercontent.com/4078392/129257395-5baa28a1-433f-4caf-9b88-59b697d0b967.png)

This is the first commit that uses Libresprite as a name for the project:
![image](https://user-images.githubusercontent.com/4078392/129256262-34d8c075-4441-4b69-bd4d-4f12d296180c.png)

Previously the name used for this work was:
![image](https://user-images.githubusercontent.com/4078392/129257078-4fa749c4-c2e5-45bb-afb4-453403bc7ae9.png)

**Comment by Zughy** [comment]
Yes, sure, I didn't want to remove David Capello and Aseprite from the source, just add the other line. 2018 seems the more logic year then
