### ISSUE TITLE
Use either vcpkg or conan to easily compile external libraries on Windows (and MacOS?)

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#150]
After #102 got merged, compiling on Windows now looks awful and it might scare away hypothetical contributors. I've done a little bit of research and there are apparently two major Windows-compatible package managers that can make contributors' life easier.

The first is vcpkg (https://vcpkg.io), the second is Conan (https://conan.io). Both contains all the libraries people need to compile properly (I've already checked) and they're 100% cross-platform, so it's only a matter of picking one or the other I guess.
According to [this](https://www.reddit.com/r/cpp/comments/9m4l0p/conan_vcpkg_or_build2/) 3 year old Reddit thread vcpkg is the no-brainer solution, whilst Conan offers a few more utilities.

I'm planning to test both tomorrow and see how it goes. For a practical vcpkg example, this is Minetest using it on Windows => https://github.com/minetest/minetest/blob/master/README.md#a-using-vcpkg-to-install-dependencies

EDIT: according to this talk, vcpkg is a cleaner and simpler solution for what we need => https://yewtu.be/watch?v=k99_qbB2FvM . Start from 26:32 for the in-depth analysis, or 41:03 for the TL;DR (both till 43:08)

**Comment by maujin111** [comment]
> After #102 got merged, compiling on Windows now looks awful and it might scare away hypothetical contributors. I've done a little bit of research and there are apparently two major Windows-compatible package managers that can make contributors' life easier.
> 
> The first is vcpkg (https://vcpkg.io), the second is Conan (https://conan.io). Both contains all the libraries people need to compile properly (I've already checked) and they're 100% cross-platform, so it's only a matter of picking one or the other I guess.
> According to [this](https://www.reddit.com/r/cpp/comments/9m4l0p/conan_vcpkg_or_build2/) 3 year old Reddit thread vcpkg is the no-brainer solution, whilst Conan offers a few more utilities.
> 
> I'm planning to test both tomorrow and see how it goes. For a practical vcpkg example, this is Minetest using it on Windows => https://github.com/minetest/minetest/blob/master/README.md#a-using-vcpkg-to-install-dependencies
> 
> EDIT: according to this talk, vcpkg is a cleaner and simpler solution for what we need => https://yewtu.be/watch?v=k99_qbB2FvM . Start from 26:32 for the in-depth analysis, or 41:03 for the TL;DR (both till 43:08)

did you test them?

**Comment by Zughy** [comment]
Not yet, thanks to the hyper-bloated Visual Studio that it's downloading more than 2GB to allow me to compile.
However, I was able to install all the packages through `vcpkg` and that worked like a charm.
After installing vcpkg, I did:
`vcpkg install freetype giflib gtest libjpeg-turbo libpng libwebp pixman tinyxml zlib --triplet x-64 windows`

I'll let you know if it works when this lovely OS finishes downloading
