### ISSUE TITLE
My tablet won't work

### ISSUE THREAD

**Issue by GalaxyzDoneDidCoding** [LibreSprite/LibreSprite#153]
My tablet when dragged won't work at all For some reason when using any items any suggestions or help?

**Comment by maujin111** [comment]
Could you please provide more information about the softare and hardware that are you using?

**Comment by Zughy** [comment]
Hello, yes, knowing the operative system and GPU would help. Someone on Matrix/Discord pointed out how they have an XP-pen working flawlessly on their Raspbian-Lite

**Comment by Zughy** [comment]
no answer from the user + backend changed + no drivers. Closing
