### ISSUE TITLE
Outdated branches

### ISSUE THREAD

**Issue by nanoslayer** [LibreSprite/LibreSprite#197]
There are a few outdated branches in the repository that should probably be deleted.

**Comment by Zughy** [comment]
Hey there, thanks for the issue.
I've deleted most of them, but kept a few as I'm not sure whether they are still useful, like the beta branch (as we're using `master` as the dev branch anyway). Tagging @maujin111

**Comment by nanoslayer** [comment]
The other branches can probably be removed as well.

Feature branches should probably not be created in the main repository. Instead you should fork the repository and create the feature branch there, then create a pull request from your forked repository. That way we avoid cluttering the main repository.
