### ISSUE TITLE
Can and should we use existing logo?

### ISSUE THREAD

**Issue by JosefKuchar** [LibreSprite/LibreSprite#23]
This is another thing related to rebranding. Can we use existing (aseprite) logo? Even if we could i think we should create a new one.

**Comment by jjhaggar** [comment]
I think we can use it, but anyway I totally agree, we should create a new one.

Sooo I've made some new ones :) 

![ase16 comparativa2 big](https://user-images.githubusercontent.com/4078392/40881968-17607d1c-66d5-11e8-9a2a-74afd84207ab.png)
They are all 16x16 pixels, that way we'll be able to scale them pixel-perfect. I have numbered them so we can talk about them. 

I've also uploaded a 300% sized version here: https://i.imgur.com/4cZIWyp.png

If anybody else want to try creating some more ones, that would be great, and after a while we could choose the one we like most :)

**Comment by akien-mga** [comment]
I agree about changing the logo, that would be good to prevent confusion between the two projects.

I quite like 1, 2 and 3, as they still have some link with the smiley-like Aseprite logo, while being clearly different.

**Comment by JosefKuchar** [comment]
I would go for 1.
PS: There are the icon files ;) https://github.com/LibreSprite/LibreSprite/tree/master/data/icons

**Comment by jjhaggar** [comment]
Since the general feeling seems to be that the new icons should have some link to the old Aseprite ones, I used #1 to create all the icons and made a pull request ;)

**Comment by JosefKuchar** [comment]
I'm not sure if we want to change the file icons. There are two options:

1. Make new file extension
2. (try to) Keep the compability between LibreSprite and Aseprite

**Comment by jjhaggar** [comment]
@JosefKuchar I fear I don't fully understand your last comment ^^U Didn't you suggested the logo/icon change? 

I think changing the logo/icon is a good idea, that way if somebody has both programs installed (s)he will know if the default program associated with .ase files is Aseprite or Libresprite. Are you now having second thoughts? Is there any drawback that I missed out? :S

And about the file extensions, (probably we sould talk about it in another thread, but) I think that we should try to keep the compatibility/file extension. 

If there will not be any differencies between the file types that LibreSprite will be using and the Aseprite ones (remember that rigt now there isn't anybody actively developing LibreSprite), and Aseprite is keeping backwards compatibility  (as it has been doing until now) I think that changing it from .ase to a new extension would be confusing and unnecesary.

**Comment by JosefKuchar** [comment]
That sounds ok

**Comment by codes404** [comment]
pls check this logo for libre sprite
![ice ](https://user-images.githubusercontent.com/96047247/145779705-3201ea77-b9a2-49fd-ac4a-954605fc66da.png)
