### ISSUE TITLE
Pixel grid rendering issue

### ISSUE THREAD

**Issue by bad-dad-games** [LibreSprite/LibreSprite#232]
##### LibreSprite version

```
v1.0-dev
```

##### Describe the bug

I have used LibreSprite 1.0 for 6 months, no issues, until yesterday. On opening programme the logo does not appear on the panel bar and the pixel grid has stopped rendering smoothly. there are jitter artifacts over the image at certain scalings when the curser is passed over the image.
##### OS/Hardware
- Operative System: Linux mint 19.1 Cinnamon
- CPU: Intel Celeron N4000 1.1ghz x2
- GPU: Intel Device 3185

##### Screenshots  ![libresprite_logo](https://user-images.githubusercontent.com/84978576/133891100-d0398ab6-c6bb-429e-9de2-7c521367468c.png)
![libresprite_pixelgrid_issue](https://user-images.githubusercontent.com/84978576/133891102-4ecf2299-73f5-4464-819b-6bee0544410b.png)

**Comment by Zughy** [comment]
I can confirm the grid, I noticed it yesterday

**Comment by bad-dad-games** [comment]
> I can confirm the grid, I noticed it yesterday. Most definitely related to the SDL2 backend switch

Thanks for the reply, what is the SDL2 backend switch, is there anything I can do to fix this?

**Comment by nanoslayer** [comment]
You can build LibreSprite with the legacy Allegro 4 backend until this issue is fixed:

```
cmake -G Ninja -DUSE_ALLEG4_BACKEND=on -DUSE_SDL2_BACKEND=off ..
ninja libresprite
```

**Comment by Zughy** [comment]
@bad-dad-games before we had an outdated backend (Allegro4) and a really annoying one (Skia). We've moved to SDL2 in these days, which is not outdated nor annoying to work with. And now we're catching/fixing bugs we missed in the first implementation. Like this one
