### ISSUE TITLE
LibreSprite icon broken on Linux since latest flatpak update

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#235]
##### LibreSprite version

```
latest commit, e1c2284
```

##### Describe the bug
The icon of the software results broken

##### To Reproduce
Download LibreSprite on a Debian/Ubuntu based version

##### Expected behaviour
See the smiling icon

##### OS/Hardware
- Operative System: Pop!_OS

##### Additional context  
More reports about it in recent issues: #232 #228

**Comment by felipemanga** [comment]
Missing a call to [SDL_SetWindowIcon](https://wiki.libsdl.org/SDL_SetWindowIcon).

**Comment by Alexander-Wilms** [comment]
Semi-related question: Do you want to have write-access to the Flatpak repository?

**Comment by Zughy** [comment]
@Alexander-Wilms I honestly don't know how it works, so I guess I'm skipping this time

**Comment by Alexander-Wilms** [comment]
Alright. The manifest gets updated automatically when there are new releases. Right now I'm just updating the manifest from time to time to use the latest Libre sprite commit.
