### ISSUE TITLE
External clipboard doesn't work on Linux

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#241]
##### LibreSprite version
```
all of them
```

##### Describe the bug
External clipboard doesn't work on Linux

##### To Reproduce
copy an image from the internet and try to paste it onto the canvas

##### Expected behaviour
paste the image

##### OS/Hardware
- Operative System: Pop!_OS
- CPU: i7

##### Additional context  
Works flawlessly (https://github.com/LibreSprite/LibreSprite-proposals/issues/8#issuecomment-922377923) on Windows

**Comment by Docmine17** [comment]
Same here and numlock not working.

**Comment by Zughy** [comment]
We're relying on a 2016 version of `clip`, which didn't have such features. It's something that David implemented only in 2018 for Linux: https://github.com/aseprite/clip/commit/8edc3a1e9a52d41505b3973b0eacb194faa263f1

I'll update it and test it in these days
