### ISSUE TITLE
Missing Libs on Appimage startup (v1.0-Beta)

### ISSUE THREAD

**Issue by workingJ** [LibreSprite/LibreSprite#253]
[Following this Issue](https://github.com/LibreSprite/LibreSprite/issues/228) i came across this:
(i could not post in the former issue thread, maybe missing rights...)

##### LibreSprite version

```
v1.0-Beta
```

##### Describe the bug
Does not start because of missing libraries.

##### OS/Hardware
 Pop!_OS 21.04 x86_64 

#### Missing Lib 1 
```
 error while loading shared libraries: libSDL2_image-2.0.so.0: cannot open shared object file: No such file or directory
```
**Fix:**
```
sudo apt install libSDL2-image-2.0-0
```
#### Missing Lib 2
```
 error while loading shared libraries: libnode.so.64: cannot open shared object file: No such file or directory
```
could not yet solve it
i tried:

```
sudo apt install libnode-dev
sudo apt install nodejs
```

edit: added codeblocks

**Comment by maujin111** [comment]
could you try again?, i updated de appimage now

https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0-beta.1

**Comment by workingJ** [comment]
Good work!
the the application has now the right name in the top panel.

the ugly preview-window-dragging-bug is gone, i can now move it fluently around!
thx! :>

**Comment by workingJ** [comment]
Good work!
the the application has now the right name in the top panel.

the ugly preview-window-dragging-bug is gone, i can now move it fluently around!
thx! :>
