### ISSUE TITLE
Master will not compile. "Target missing executable"

### ISSUE THREAD

**Issue by ElfEars** [LibreSprite/LibreSprite#26]
When attempting to build the master branch. I get the error " Target missing executable" "libresprite.exe does not have an executable configured"

Is anyone else getting this bug?

For reference, the previous stable build (1.1.7) works fine and I can compile it with no issues.
I am using Visual Studio Community Edition.

### LibreSprite and System version

* LibreSprite: (Current Master)
0a01bb9a9d6cf65868cebc7f3df346044a6b1534

* System: Windows 10

**Comment by ElfEars** [comment]
(Temporarily closing, more info has been found)

**Comment by MintStudios** [comment]
What visual studio version are you using? I find that visual studio 19 results in this problem.

**Comment by ElfEars** [comment]
Er. last time I tried was AAAAGES ago and I don't even know what version that would be.
I don't even use Visual Studio anymore so I'm afraid I can offer no help in this situation (Not that it ever worked for whatever reason)

My best tip using my modern perspective on codebases would be to run some sort of diff on the two trees to see where things have changed and thus could have gone wonky (It appears to be a solution problem so maybe you could just diff those files?)

**Comment by MintStudios** [comment]
I will close this, because it is stale. @ElfEars if you will compile this, you should use visual studio 15.
