### ISSUE TITLE
SDL2: program doesn't run properly when launching it, opening the process but without trace of it in the app bar

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#261]
##### LibreSprite version
```
latest dev
```

##### Describe the bug
Title says all

##### To Reproduce
Try to run it through CLI and
```
Unknown windowevent: 1
Unknown windowevent: 2
Minimized
Force Flip
Unknown windowevent: 10
Unknown windowevent: 12
Unknown windowevent: 15
Unknown windowevent: 11
Unknown windowevent: 4
Unknown windowevent: 13
```
no program anywhere. Must Ctrl+C and then re-launch it. These are the decoded events: https://wiki.libsdl.org/SDL_WindowEventID

##### OS/Hardware
- Operative System: Pop!_OS 21.04
- CPU: i7 7700
- GPU: GTX 1060

##### Additional context  
This doesn't happen with Allegro as a backend, hence "SDL2" in the title

**Comment by godofgrunts** [comment]
I just compiled the latest dev with and it opens and runs for me. What version are you on?

```
$ git rev-parse --short HEAD
4e184e34c
```

**Comment by Zughy** [comment]
I'm always on the latest commit, and it's a SDL2 issue, as Allegro doesn't give me any issue (I've just tested). I'll update the first message

**Comment by godofgrunts** [comment]
I assume that as long as I don't use `-DUSE_SDL2_BACKEND=off -DUSE_ALLEG4_BACKEND=on` I'm on SDL2 right? Maybe it's an issue with Pop's version of SDL2? I'm on 2.0.16.

```
$ sdl2-config --version
2.0.16
```

**Comment by Zughy** [comment]
Pop!_OS latest version is `2.0.14`, so I'm on that
