### ISSUE TITLE
What’s the progress on the website?

### ISSUE THREAD

**Issue by andersonaddo** [LibreSprite/LibreSprite#27]
Hi guys!
So I’ve just stumbled upon this repo, and I looked at #1. It looks like some of the contributors were up for making a website, but nothing left had been done. I’m wondering what the plan for the website is. 

It’d really help put this project out there (LibreSprite is a noble cause!), and as said in #1, it’ll make this repo seem like more of a serious project. 
Also, it’ll make it much easier for people to get their hands on the software.

**Comment by ElfEars** [comment]
Eh. This repo is pretty dead TBH.

A website would be good though. It might be able to attract some people to the cause.

Aseprite is WAAAY easier to mess about with than competing efforts such as gimp.

**Comment by MagicFab** [comment]
At least the libresprite[.com|.net|.org] domains were registered on 2018-06-08 at the same time (presumably by the same person) and forward to this repository.

**Comment by DustinVFP** [comment]
is anyone actually working on a webpage for libresprite at the moment?

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Nobody is working on this. Spend 20 bucks and get the actual program.

**Comment by wcbx** [comment]
Don't spend 20 bucks on the program. There are so many better free alternatives out there. It's not worth it.

**Comment by jjhaggar** [comment]
Well, Aseprite is a really good pixel art oriented program, the best right now in my opinion, so I don't think is a bad thing to support its developers (also, they are really nice people). I actually try to support them by buying it for myself and some of my friends.

On the other hand, for multiple reasons I would also love that Aseprite would continue being free/libre as it started, hence my interest in LibreSprite. I could work on a webpage, but not on the program itself (I am not capable even of making a build ^^U) so while its development is stopped I think there is no point on making the website. If anybody is interested on continue developing LibreSprite just tell me and I'll help with the website.

To be honest there are not better free alternatives than Aseprite for pixel art, yeah you can use some really good software like Krita or Gimp, but they are not really pixel art oriented, so some of its key functionalities can only be found on that program. 

Anyway, anyone should decide if they want to spend 20 bucks or not by deciding if it's worth it or not for themselves. Both decisions are respectable.

**Comment by wcbx** [comment]
https://lospec.com/pixel-art-software-list

Here is a list I found by googling. There are a myriad of programs that are either just as good or even better. It's not worth 20 bucks.

**Comment by jjhaggar** [comment]
With due respect, I beg to differ. Except for PikoPixel I have already tested all that software on the list, and feature-wise there is objectively no comparison, Aseprite wins by a landslide. Well, I mean for pixel art, of course, if not Krita would be the winner.

**Comment by wcbx** [comment]
Piskel is much better and free.

**Comment by akien-mga** [comment]
Alright, let's put an end to the offtopic discussion here.

As a reminder, this repository is an archival of the last FOSS version of Aseprite, which was subsequently rebranded to prevent confusion. Nobody proposed to become the new maintainer, so this project is currently abandoned until someone decides to take it over.

What pixel editing tools are best is completely offtopic - if you're interested in both Aseprite and open source software, this repository can be of interest to you, otherwise use the other tools you prefer.
