### ISSUE TITLE
cant type a "_" in the filename of a save image dialouge

### ISSUE THREAD

**Issue by MisterE123** [LibreSprite/LibreSprite#271]
##### LibreSprite version
1.0-dev
```

```

##### Describe the bug
I can't type an underscore in the filename
##### To Reproduce
try to save a file and use an underscore in the filename

##### Expected behaviour
should be able to use any normal symbols

##### OS/Hardware
- Operative System: Linux Mint

**Comment by felipemanga** [comment]
I just tested with the latest build and couldn't replicate the issue.
Looks like it has been fixed already.

**Comment by MisterE123** [comment]
ok. I guess the linux mint repo is out of date

**Comment by Zughy** [comment]
It works here too. Can you please try to [compile](https://github.com/LibreSprite/LibreSprite/blob/master/INSTALL.md) the master branch and tell us if you still have this problem?

**Comment by felipemanga** [comment]
I'll close this issue since it seems to have been fixed. Feel free to open a new one if there is still something wrong.
