### ISSUE TITLE
AppImage 1.0-beta.1 missing libtinyxml.so.2.6.2

### ISSUE THREAD

**Issue by superjamie** [LibreSprite/LibreSprite#273]
Starting the [current 1.0-beta.1 release](https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0-beta.1) on Ubuntu 20.04 results in the error:

~~~
./libreSprite-x64-pre-release.AppImage 
/tmp/.mount_libreShqa7Kp/usr/bin/libresprite: error while loading shared libraries: libtinyxml.so.2.6.2: cannot open shared object file: No such file or directory
~~~

This can be worked around by installing the required library:

~~~
sudo apt install libtinyxml2.6.2v5
~~~

So it seems the AppImage is accidentally missing this library.

I couldn't see the AppImage build script anywhere in the repo, so seems I cannot offer a PR to fix this myself.

**Comment by Zughy** [comment]
We're having a few issues with the appimage and we're considering to use a CD through GitHub Actions

**Comment by Zughy** [comment]
Closing as a new release will be out soon with a stable appimage. We're running some tests and for now it's worked on 3 out of 3 different distros (Debian, Pop!_OS and Mint)
