### ISSUE TITLE
Build instructions are for macOS 10.11 but something requires version 11.0 or later to run the program

### ISSUE THREAD

**Issue by Ojas-dev** [LibreSprite/LibreSprite#281]
When I open the app it gives this message:

![Screenshot 2021-10-06 at 10 05 08 AM](https://user-images.githubusercontent.com/61822816/136141272-d58c5cd4-7f17-4574-bc33-41f15eb7362b.png)

**Comment by Justiniscoding** [comment]
I also have this problem on macOS 10.11.6 El Capitan.
![Screen Shot 2021-10-14 at 9 03 54 AM](https://user-images.githubusercontent.com/76059890/137323017-6670dad8-08e5-400c-8788-9824c8629253.png)

**Comment by Ojas-dev** [comment]
Justiniscoding, 
You should try to right click on the app, click show package contents, then open the MacOS folder and run the unix executable if that does not work then I don't know I am not a mac expert

**Comment by Zughy** [comment]
Almost a month has passed and, since no one stepped up to handle this Mac issue, we've just updated the required version to 11.0. We're sorry but we don't have the necessary machines to test and (try to) fix this issue - or in general to maintain Macs - hence I'm closing
