### ISSUE TITLE
Lag spikes and 100% CPU usage when dragging the canvas.

### ISSUE THREAD

**Issue by Gaarco** [LibreSprite/LibreSprite#289]
##### LibreSprite version
`5b40aa8520859d827725cbc59d4a7ac79cc84848`

##### Describe the bug
When I drag the canvas the CPU usage goes to 100% and if the window is maximized I experience lags, just once the application froze for some seconds.

##### To Reproduce
Create a new blank canvas and start dragging it.

##### Expected behaviour
100% CPU usage doesn't seem to be an expected behavior but what bothers me are the lags when the window is maximized.

##### OS/Hardware
- Operative System: Arch Linux
- CPU: i7 7700HQ
- GPU: GTX 1050 Mobile

**Comment by Zughy** [comment]
Hello, and thanks for the report.
I've been currently using the latest dev commit version for days with an i7 7700 and I've encountered no problems. Out of curiosity, what's your screen resolution?

**Comment by Zughy** [comment]
This is definitely a problem because our intent is to drop Allegro support as soon as SDL2 results stable. We have basically the same PC components and it works flawlessly on Arch, so I can't really understand why this happens

**Comment by felipemanga** [comment]
Closing since this has probably been fixed by now. Feel free to re-open if that's not the case.
