### ISSUE TITLE
Incomplete sources in latest pre-release (1.2-973d0e3d)

### ISSUE THREAD

**Issue by delightedcat** [LibreSprite/LibreSprite#298]
##### LibreSprite version

```
1.2-973d0e3d
```

##### Describe the bug

While attempting to write an ebuild (installation) script for the Portage package manager, I came to the conclusion that the source provided with the latest pre-release (v1.2-973d0e3d) does not include any submodules. This makes the source incomplete and impossible to turn into a reliable package because it's not possible to compile without said submodules.

##### To Reproduce

Download the source code of the [the latest pre-release](https://github.com/LibreSprite/LibreSprite/releases/tag/v1.2-973d0e3d) in `.tar.gz` format and open one of the submodule directories. You will observe the directories are in fact empty.

##### Expected behaviour

The third-party submodule sources should be included in the source tarball in order to turn the release of the code into a reliable and stable package.

##### OS/Hardware
- Operative System: Gentoo GNU/Linux (x86_64)
- CPU: Intel i7-10700KF (16) @ 5.100 GHz

**Comment by Zughy** [comment]
Hello, and thanks for reporting this.
I've looked into how tar.gz packaging works, and this is what I've found about submodules. We could implement something similar I guess https://github.com/materialx/MaterialX/issues/317

**Comment by delightedcat** [comment]
Thank you for the reply. I looked into the link you posted, and it seems to be a reasonable solution, although I gave the script a try on a fork I took of LibreSprite, and it seems to handle things a bit differently.

It seems to make a *separate* tarball for each submodule, although ideally the complete source as how it should be compiled should be available, otherwise you'd probably need to have each submodule's sources listed separately each release. Another problem I seem to find with the script is that it creates a tarball *inside* each submodule's directory, meaning that it messes with and invalidates each submodule since it adds a new file to the submodule directory.

That's why I hacked together a quick script that would take the current repository, clean it and archive it. This would produce a clean source tarball that can be compiled directly. The said script can be found [here](https://git.sr.ht/~delightedcat/dotfiles/tree/trunk/item/scripts/git-archive-source.sh).

Some quick instructions to get it up and running to see it in action:
```
cd /path/to/LibreSprite
wget https://git.sr.ht/~delightedcat/dotfiles/blob/trunk/scripts/git-archive-source.sh
chmod +x git-archive-source.sh
./git-archive-source.sh
```
A tarball with the full and cleaned up sources should now be available in the current directory. The script will tell you where the tarball is placed. This tarball should be complete and ready to compile right away.

**Comment by Zughy** [comment]
So, uhm, I thought that the tarball could be manually replaced, but it doesn't seem to be the case on GitHub (we've just released 1.0 with the same problem). Do you happen to know how to automatically implement your script in the delivery process? Unfortunately I don't know much about this aspect

**Comment by delightedcat** [comment]
I'm not sure how releases normally handle this on GitHub, but I do know that this kind of stuff is usually handled through GitHub Actions. I've never implemented such thing myself though. I think GitHub just adds the current snapshot of the code for each release, and the problem here is that it doesn't include any submodules.

A quick search turned up that it does seem pretty common to include a custom archive to GitHub releases, I found [this article on the subject](https://trstringer.com/github-actions-create-release-upload-artifacts/) for example. Whereas this example includes actual build artifacts, it would be possible to include the full source instead as well.

**Comment by Zughy** [comment]
I did my homework and apparently it's been *years* people have been [asking for submodules to be included](https://github.community/t/create-release-that-contains-submodule/1329). With an employee basically saying "we hear you!" but without providing any official answer: this is simply ridiculous. So, no, there is no way we can swap the default zips and tarballs with custom ones, not manually nor automatically.

The only solution, as you rightly pointed out, is to automatically attach *additional* files via GitHub Actions. That means having both the automatically generated uncompleted ones and the correct ones in every release. I think it goes without saying that such approach is a messy band-aid and, even more important, something we shouldn't even spend time to implement as I expect it to be a default option. But hey, I guess implementing the "Discussions" feature was way more important than avoiding providing broken releases.

I'm having a look at GH Actions, hopefully in these days I should be able to fix it

**Comment by Zughy** [comment]
Well, zip is working (https://github.com/Zughy/LibreSprite/releases/tag/test), I'll have a look for the tar tomorrow

**Comment by delightedcat** [comment]
I couldn't agree more, this feature seems to be very needed if not critical. The same thing happened with us waiting for a proper dark theme on GitHub for years with employees telling us they hear us. It is a messy "band-aid" solution indeed, but it seems there's no good alternative option. 

As for the zip; this would be a perfect solution to properly compile the full release. I completed most of the ebuild script for LibreSprite and I'm in fact using it on my Gentoo system as of right now. It's placed in a local overlay repository now for experimentation, but I'm looking to get the ebuild into the official Gentoo repository. The Aseprite ebuild hasn't been updated since version 1.1.9, most likely due to the change in licensing.
