### ISSUE TITLE
Unable to compile v1.0 with gcc7

### ISSUE THREAD

**Issue by ekaitz-zarraga** [LibreSprite/LibreSprite#303]
##### LibreSprite version

```
v1.0
```

##### Describe the bug

Unable to compile from source.
I'm trying to compile the software from source and even if it configures correctly there are compilation errors when the 84% of the compilation is done: error messages are attached.

##### To Reproduce

Compile the software using CMake and GCC

##### Expected behaviour

Software compiles correctly

##### OS/Hardware
- Operative System: Guix System (Linux based distro)
- CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz

##### Additional context  

[error.txt](https://github.com/LibreSprite/LibreSprite/files/7562407/error.txt)

UPDATE: it was related with the compiler. GCC10 does not have this compile time issue.
We should update the documentation accordingly.

**Comment by maujin111** [comment]
This issue can be solved updating the GCC version to 10 or higher
