### ISSUE TITLE
deb file?

### ISSUE THREAD

**Issue by JoshS** [LibreSprite/LibreSprite#31]
I'm running ubuntu 18.04 and would like to use this, if anyone has a deb file that would be appreciated. :)

**Comment by cauehsf** [comment]
Hey, Libresprite is available on Flatpak Store. But has some problems (at least to me), if the source code works well on your computer, go ahead and try out the Flatpak version.

**Comment by MintStudios** [comment]
@JoshS the appImage is available on the website.
https://libresprite.github.io
