### ISSUE TITLE
Can't compile on OpenSUSE: freetype library missing

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#318]
##### LibreSprite version
```
doesn't really matter
```

##### Describe the bug
cmake can't find the freetype library, even if I have `libfreetype6`, `libfreetype6-32bit` and `freetype2` installed

##### To Reproduce
Try to compile

##### OS/Hardware
- Operative System: OpenSUSE 64bit (Tumbleweed 2021119)

##### Additional context  
Running on a VM but it shouldn't matter

**Comment by teh404guy** [comment]
This issue is old
But saying for anyone having problems
Try finding the packages that end with -dev or -devel
Those help with compiling

**Comment by maujin111** [comment]
any luck with the solution provide above?

**Comment by stoecker** [comment]
Package builds in games:tools and also in Tumbleweed directly: https://build.opensuse.org/package/show/games:tools/libresprite. You should close this issue.
