### ISSUE TITLE
Link to Windows Installer is missing from the Downloads page

### ISSUE THREAD

**Issue by NickJH** [LibreSprite/LibreSprite#324]
If you go to https://libresprite.github.io/#!/downloads there is a link to the Windows Installer but it just takes you to https://github.com/LibreSprite/LibreSprite/releases where there is no installer.

**Comment by Zughy** [comment]
Yes there is, there are two windows zips in there. These ones
![image](https://user-images.githubusercontent.com/63455151/144774039-a6537343-04f2-4979-8165-36ecd9afd453.png)

Actually, are those ones installers or portable versions? I've never tried them, as I wasn't the one who compiled them

**Comment by NickJH** [comment]
They are not installers, or, at lease the x86_64 one is not. It is portable? You can unzip it and great a shortcut to the executable but it is not an installer whereas one of the older versions which I was using had an installer which you could see through Add/Remove Programs.
