### ISSUE TITLE
LibreSprite Crash Report because it wanted me to.

### ISSUE THREAD

**Issue by K1ZANA** [LibreSprite/LibreSprite#334]
##### LibreSprite version

```
LibreSprite v1.2-973d0e3d-SDL
```

##### Describe the bug

I´m reporting this because it wanted me to, i dont know why tho.
##### To Reproduce

I´m reporting this because it wanted me to, i dont know why tho.
##### Expected behaviour

I´m reporting this because it wanted me to, i dont know why tho.
##### OS/Hardware
- Operative System: Windows 11 x64 Version 21H2 (OS Build 22000.376)
- CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
- GPU: 

##### Crash Dump

https://pastebin.com/wJPNK3w2

**Comment by not-avai** [comment]
ok,there is no way someone can be this dumb.
look,just delete this,ok?
just delete this.

**Comment by K1ZANA** [comment]
this issue was literally posted over 4 months ago, you´re dumb for even looking at shit thats this old. god.
