### ISSUE TITLE
Allow build from release tar.gz

### ISSUE THREAD

**Issue by Eragonfr** [LibreSprite/LibreSprite#335]
Currently the cmake file depends on git sub-modules.
Theses sub-modules are not included in the release tarball.
It's better to be able to download the tarball and build everything from that tarball.
No sub-modules involved.
Maybe it's just missing doc to explain how to do that. Or it's related to cmake.
But please allow users to build from the tarball

**Comment by Zughy** [comment]
This has been fixed already through #306 , but it needs a new release to be noticed
