### ISSUE TITLE
Mentioned MacOS App can't be found.

### ISSUE THREAD

**Issue by baermathias** [LibreSprite/LibreSprite#338]
The README states the following: 

Grab an [AppImage](https://github.com/LibreSprite/LibreSprite#:~:text=Grab%20an-,AppImage,-for%20Linux%2C%20macOS) for Linux, macOS [App](https://github.com/LibreSprite/LibreSprite#:~:text=for%20Linux%2C%20macOS-,App,-or%20get%20the) or get the [Windows Portable](https://github.com/LibreSprite/LibreSprite#:~:text=or%20get%20the-,Windows%20Portable,-.).

But:

- There is no `macOS App`. 
- The `AppImage` leads to an old link.
- The `Windows Portable` link is a 404 error

**Comment by baermathias** [comment]
@maujin111 So there is no release for macOS? Will there be one in future?

**Comment by jjhaggar** [comment]
We are working on that, but it's not easy I'm afraid ^^U And if I'm not wrong we still don't have a developer who has got a Mac to build the binaries.

**Comment by maujin111** [comment]
> @maujin111 So there is no release for macOS? Will there be one in future?

It is possible to compile for macOS
