### ISSUE TITLE
Not Running on Windows. (Both 32bit and 64 bit). System is 100% fine, 

### ISSUE THREAD

**Issue by AryamanJoshi** [LibreSprite/LibreSprite#344]
I'm not able to open LibreSprite on my system at all. This is weird as it was working perfectly the previous night and then it just stopped working when I tried to to run the app the next morning. Reinstalled, tried 32bit and 64bit, restarted PC, updated Windows. Nothing works. There seems to be no issue with my laptop, it seems fine. 

What's happening: The icon is showing up in the taskbar but the app window isn't opening. 

Let me know if there's anything else you'd like to know!
Thanks,

**Comment by piratesephiroth** [comment]
It might be just offscreen then.
Go to Edit -> Preferences -> Locate Configuration File

Open libresprite.ini and check the values in the "WindowLayout" line
