### ISSUE TITLE
Crash - Might have been my system not the app but it wanted me to report.

### ISSUE THREAD

**Issue by Linux-Gamer** [LibreSprite/LibreSprite#345]
I was trying to use the text tool to make an asset for a game, and it crashed. Again, might have been my system, but the app wanted me to report.

**Comment by Linux-Gamer** [comment]
I just tried it again on a different install of libresprite (same version) and it has done it again, when choosing font in the text popup,  the whole app crashes

**Comment by Linux-Gamer** [comment]
it's on windows

**Comment by maujin111** [comment]
Let me see if i got the same error

**Comment by maujin111** [comment]
Duplicate of #343
