### ISSUE TITLE
Appimage not having support for themes or scripts.

### ISSUE THREAD

**Issue by Linux-Gamer** [LibreSprite/LibreSprite#347]
![image](https://user-images.githubusercontent.com/83363242/151952816-731515ed-c0ec-4e0a-8dd6-51faa51e37b8.png)

I am currently running it on Kubuntu Latest release, with the official appimage just downloaded from the website.

**Comment by maujin111** [comment]
Have you tried to enter manually on the folder "/home/user/.config/libresprite/data"?

**Comment by Linux-Gamer** [comment]
Found out that you need to build the directory for the app image to support themes and scripts
