### ISSUE TITLE
App crashes when selecting font in text menu

### ISSUE THREAD

**Issue by Linux-Gamer** [LibreSprite/LibreSprite#351]
Libresprite crashes when selecting the font in text menu.

### Steps To Reproduce
- Open Libresprite.
- "T"
- select font
- then crash

###### OS
Windows 11
###### LibreSprite Version
V 1.0

**Comment by maujin111** [comment]
i tried to replicate the bug and had not success, i'm on windows 10

**Comment by maujin111** [comment]
Duplicate of #345
