### ISSUE TITLE
Themes don't work properly where text can be.

### ISSUE THREAD

**Issue by pixlxip** [LibreSprite/LibreSprite#355]
##### LibreSprite version

```
1.0-dev
```

##### Describe the bug

The boxes where text would go if it was long enough isn't affected by themes.
##### To Reproduce

Try a dark theme (to see the issue more clearly) while using the 1.0-dev version, using Winebottler (with Winetrick "win10"), on MacOS El Capitan 10.11.6.
##### Expected behaviour

Theme colour should spread behind the text and around it.
##### OS/Hardware
- Operative System: MacOS El Capitan 10.11.6
- CPU: 2 Quad-Core Intel Xeon
- GPU:  ATI Radeon HD 5770

##### Screenshots  

![Screen Shot 2022-03-09 at 5 15 25 PM](https://user-images.githubusercontent.com/99521063/157565312-bb36d8bd-f846-4518-930e-49e240a986b5.png)

##### Additional context  

This probably wouldn't happen if somebody was actually using Windows 10 and might just be my circumstances or Winebottler.

**Comment by Linux-Gamer** [comment]
Seems like an issue with the theme code for the text bit, ik there is a bit of the code that does this

**Comment by pixlxip** [comment]
> Seems like an issue with the theme code for the text bit, ik there is a bit of the code that does this

I checked with two packs. I'll test some more for now
