### ISSUE TITLE
Flatpak version out of date

### ISSUE THREAD

**Issue by ChildishGiant** [LibreSprite/LibreSprite#357]
The [flatpak](https://github.com/flathub/com.github.libresprite.LibreSprite) is still at v1.0

**Comment by Linux-Gamer** [comment]
That isn’t out of date, that's the latest release version. :)

**Comment by ChildishGiant** [comment]
Ah I thought there was v1.2 from this https://github.com/LibreSprite/LibreSprite/commit/8fa1f8959e02464fb3edbb9d6804fed977b09a21

**Comment by Linux-Gamer** [comment]
Not a release afaik

**Comment by Linux-Gamer** [comment]
Cos of Dotto, it being easier to rewrite than reorganise the code, no new things were added to Libresprite
