### ISSUE TITLE
Run prompt cannot find VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by Yakumo-Yukari** [LibreSprite/LibreSprite#358]
LibreSprite-Windows-x86_64 version

**Comment by maujin111** [comment]
Try installing [this](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) 
![image](https://user-images.githubusercontent.com/25780951/166204319-aa6f708e-2240-4beb-be98-d44376778f25.png)
Install both

**Comment by Yakumo-Yukari** [comment]
> Try installing [this](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) ![image](https://user-images.githubusercontent.com/25780951/166204319-aa6f708e-2240-4beb-be98-d44376778f25.png) Install both then restart

Does LibreSprite support other languages? What file should I change if I want to support other languages? Or what file should be added to make it international?

**Comment by maujin111** [comment]
For now, it does not support any other languages. Did Installing those files fix the problem?

**Comment by Yakumo-Yukari** [comment]
> For now, it does not support any other languages. Did Installing those files fix the problem?

Yes, it works fine after installing the dll
