### ISSUE TITLE
Compilation error related to Lua 

### ISSUE THREAD

**Issue by piface314** [LibreSprite/LibreSprite#359]
##### LibreSprite version

```
1.0
```

##### Describe the bug

After following the build instructions (`cmake -G Ninja ..` then `ninja libresprite`), I get a compilation error, pointing that some constants and functions related to Lua are not defined.

```
[239/725] Building CXX object src/scri...eFiles/script-lib.dir/lua/engine.cpp.o
FAILED: src/script/CMakeFiles/script-lib.dir/lua/engine.cpp.o 
/usr/bin/c++  -DHAVE_CONFIG_H -DNDEBUG -DSCRIPT_ENGINE_LUA=1 -DSCRIPT_ENGINE_V8=1 -DUSE_SDL2_BACKEND -DV8_COMPRESS_POINTERS -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/lua5.1 -I/usr/include/nodejs/deps/v8/include -I../third_party/simpleini -I/usr/include/SDL2 -I../src/. -I../src/.. -I../src/../third_party -I../src/observable -Isrc/base -I../third_party/duktape -std=c++14 -Wall -Wno-switch -std=gnu++11 -std=c++14 -O2 -g -DNDEBUG -MD -MT src/script/CMakeFiles/script-lib.dir/lua/engine.cpp.o -MF src/script/CMakeFiles/script-lib.dir/lua/engine.cpp.o.d -o src/script/CMakeFiles/script-lib.dir/lua/engine.cpp.o -c ../src/script/lua/engine.cpp
../src/script/lua/engine.cpp: In function ‘int luaopen_array(lua_State*)’:
../src/script/lua/engine.cpp:77:3: error: ‘luaL_setfuncs’ was not declared in this scope; did you mean ‘lua_setfenv’?
   77 |   luaL_setfuncs(L, arraylib, 0);
      |   ^~~~~~~~~~~~~
      |   lua_setfenv
../src/script/lua/engine.cpp: In member function ‘virtual bool LuaEngine::eval(const string&)’:
../src/script/lua/engine.cpp:124:47: error: ‘LUA_OK’ was not declared in this scope; did you mean ‘LUA_QL’?
  124 |       if (luaL_loadstring(L, code.c_str()) == LUA_OK) {
      |                                               ^~~~~~
      |                                               LUA_QL
```

##### To Reproduce

I just followed the default installation instructions:
```
git clone --recursive https://github.com/LibreSprite/LibreSprite
cd LibreSprite
sudo apt-get install cmake g++ libcurl4-gnutls-dev libfreetype6-dev libgif-dev libgtest-dev libjpeg-dev liblua5.4-dev libpixman-1-dev libpng-dev libsdl2-dev libsdl2-image-dev libtinyxml-dev libnode-dev ninja-build zlib1g-dev
mkdir build
cd build
cmake -G Ninja ..
ninja libresprite
```

However, `liblua5.4-dev` was not present in `apt`, so I installed it [manually](https://www.lua.org/manual/5.4/readme.html).

##### OS/Hardware
- Operative System: Ubuntu 20.04
- CPU: Intel® Core™ i5-5200U CPU @ 2.20GHz × 4

##### Additional context  

As a programmer who uses Lua frequently, I have multiple versions installed, namely: LuaJIT, 5.1, 5.3 and 5.4. I noticed `cmake -G Ninja ..` tries to detect the Lua version in use. This is the output I got:

```
-- Found Lua: /usr/local/lib/liblua.a;/usr/lib/x86_64-linux-gnu/libm.so;dl (found version "5.1.5")
```

This `/usr/local/lib/liblua.a` file was created yesterday, when I installed 5.4 from source as stated before. Despite this, cmake still says it's version 5.1.

**Comment by piratesephiroth** [comment]
I think you can make it ignore the undesired lua library paths with [-DCMAKE_IGNORE_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_IGNORE_PATH.html)

**Comment by piface314** [comment]
So this time I ran the following command instead: 
```
cmake -DCMAKE_IGNORE_PATH="/usr/include/lua5.1;/usr/share/lua5.1;/usr/share/man/man1/lua.1.gz;" -G Ninja ..
```
and it says:
```
-- Could NOT find Lua (missing: LUA_INCLUDE_DIR)
```
Even though I'm sure Lua 5.4 is installed, and the environment variable `LUA_INCLUDE_DIR` is set. Despite this, the build apparently has finished successfully. Does that mean a specific feature will be unavailable?

**Comment by Linux-Gamer** [comment]
Try “sudo apt install lua” or whatever the package name is on apt and see if it installs

**Comment by maujin111** [comment]
`sudo apt install liblua5.4-dev` should work

**Comment by winterheart** [comment]
See #291.

**Comment by felipemanga** [comment]
Closing since support for Lua has been dropped.
