### ISSUE TITLE
Revive this please

### ISSUE THREAD

**Issue by xslendix** [LibreSprite/LibreSprite#36]
title says it all

**Comment by cartufer** [comment]
^

**Comment by Rasmez** [comment]
^x2

**Comment by akien-mga** [comment]
Are you volunteers to do it?

This repository is just an archive, there's no active maintainer.
https://github.com/LibreSprite/LibreSprite/issues/1#issuecomment-394152050

**Comment by cartufer** [comment]
Can someone at least put up a compiled exe so i don't have to setup everything needed?
