### ISSUE TITLE
No Export Button For Libresprite

### ISSUE THREAD

**Issue by Elmntz** [LibreSprite/LibreSprite#362]
##### LibreSprite version

```
Libresprite V.1.2
```

##### Describe the bug

I do not know why, but there is no button to export my animation in libresprite. I do not know if there should be one there, but I think it is being replaced with a "save copy as" button

##### To Reproduce

Running Libresprite
##### Expected behaviour

I want to export an animation and I can not
##### OS/Hardware
- Operative System: Windows 10
- CPU: I5 10400f

##### Screenshots  

![image](https://user-images.githubusercontent.com/75771081/172733786-92235a3f-96ff-46e7-952a-19bfda6bedf6.png)

**Comment by maujin111** [comment]
it is under the 'Save as' option

**Comment by Elmntz** [comment]
> 

It is not there for me. As you may be able to see in the screenshot, Export does not show up for me.

**Comment by maujin111** [comment]
There is no export button, the button it's call 'save as'use that to export

**Comment by Elmntz** [comment]
Ohhh Okay Thanks! What format would I use to export the animation?

**Comment by jjhaggar** [comment]
.gif format

**Comment by Silabear** [comment]
Sorry... I'm looking to export it as higher quality, how?
