### ISSUE TITLE
Cannot build on mac due to 32bit symbols

### ISSUE THREAD

**Issue by cheepling** [LibreSprite/LibreSprite#363]
##### LibreSprite version
Built off the source code
```

```

##### Describe the bug
When trying to build both aseprite and libresprite, I get to the very end of the process where ninja attempts to link the executable. At this point it comes up with a series of errors which culminate in 
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

##### To Reproduce
     1. Follow the installation steps on any OS without 32bit support
     2. Wait for compilation
     3. Observe error message.

##### Expected behaviour
Even if it isn't possible to create a mac installer, it would be appreciated if you could make a version with 32bit dependencies. I am experimenting with dual booting linux and will see how build goes, but I feel a lot of people would like to be able to use libresprite who can't due to their OS.

##### OS/Hardware
- Operative System: MacOS 11.6.5 Big Sur
- CPU: 1.7 GHz Dual-Core Intel Core i7
 

I feel most people who have had issues downloading it would be on a m1 chip or some other form of arm hardware, which is probably why I've been having issues. It could be an issue with ninja but it seems to be specific to the 32bit dependencies of aseprite and libresprite.

**Comment by maujin111** [comment]
Verify library paths: Ensure that the necessary libraries are correctly specified in the linker flags or settings. Make sure the paths to the libraries are accurate and include the required architecture (x86_64 in this case). Any way, there is a [new relesease for macOS](https://libresprite.github.io/#!/downloads)
