### ISSUE TITLE
Portable (.zip) LibreSprite writes to registry on Windows

### ISSUE THREAD

**Issue by veganaize** [LibreSprite/LibreSprite#373]
##### LibreSprite version

```
1.0 and 1.1-dev (ed8d6ce6cb32d574905b724ef4959d05ac42102b)
```

##### Describe the bug

When LibreSprite (_any bitness_) is extracted to a folder & run it seems to write to the registry because, when another instance of LibreSprite is extracted in a separate folder & run, it crashes if the theme of the first instance isn't available (to the second instance).

##### To Reproduce

1. Unpack LibreSprite to a folder such as C:\LibreSprite
2.  Unpack a theme (such as [Zero Dark](https://github.com/ZeroAlvein/LibreSprite-Zero-Dark-Theme/archive/refs/heads/main.zip) into the `data\skins` subdirectory, under that binary's location.
3.  Run that instance of `libresprite.exe`
4.  Apply theme in `Edit` -> `Preferences` -> `Theme`
5.  Unpack a new instance of LibreSprite into some other folder
6.  Run the new instance of `libresprite.exe`
7.  Observe the error...
![image](https://user-images.githubusercontent.com/7102064/186799305-fb35c9e8-23af-4ef8-92f7-381b28ce61bb.png)

##### Expected behaviour

New portable instances of LibreSprite should probably save & load their settings to & from an `.ini` file or else automatically revert to the default theme, instead of throwing an error, when some other theme can't be found.

##### OS/Hardware
- Operative System: Windows 8.1 (64-bit)
- CPU: AMD A6 Quad Core

**Comment by felipemanga** [comment]
Closing since this issue has been fixed.
