### ISSUE TITLE
Is `curl` a required dependency if the updater is disabled at build-time?

### ISSUE THREAD

**Issue by throwaway1037** [LibreSprite/LibreSprite#374]
If not, the docs should be updated to reflect this.

**Comment by maujin111** [comment]
it is, the CMakeLists.txt of libresprite has this line:
```
find_package(CURL REQUIRED)
include_directories(${CURL_INCLUDE_DIRS})
```

so no matter if updater is disabled or not cmake will always try to find curl and if it doesn't find it, it will not generate the build files...
