### ISSUE TITLE
Color picking with alt+click does not work

### ISSUE THREAD

**Issue by devnewton** [LibreSprite/LibreSprite#376]
##### LibreSprite version
v1.0-dev ( downloaded from https://github.com/LibreSprite/LibreSprite/releases/download/v1.0/libresprite-Linux-x86_64-Debian_10.AppImage )

##### Describe the bug

Picking color with pencil tool and ALT+left button click does not change current color.

##### To Reproduce

Select pencil tool then ALT+left button click on an image.

##### Expected behaviour
Current color should be set as clicked pixel color.

##### OS/Hardware
- Operative System: Debian GNU/Linux 11
- CPU: x86_64

**Comment by maujin111** [comment]
I tried on macOS and works fine, anyone else can confirm the bug?

**Comment by jjhaggar** [comment]
I tried on Windows 10 and it also works fine. 
Maybe it's a Debian problem? Could anybody who is also using Debian try and confirm the problem, please?

**Comment by devnewton** [comment]
I have found the origin of the bug : I use XFCE as my desktop environment.

The default settings of his window manager (xfwm) use ALT+Click as a shortcut.

To disable this you need to:

- launch xfce4-settings-manager
- click "settings editor"
- select xfwm4 in the left pane
- in the right pane, change the value of easy_click  from "Alt" to nothing

![image](https://user-images.githubusercontent.com/103828758/208929220-9232df6e-15df-4699-991b-92d2f98360b8.png)
