### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by SenzelXPH** [LibreSprite/LibreSprite#379]
Object VCRUNTIME140_1.dll not found. I am a basic desktop user so I don't know how to fix it. I installed everything again and it still doesn't work.

**Comment by jjhaggar** [comment]
Hi, here's a solution for that issue: https://github.com/LibreSprite/LibreSprite/issues/358#issuecomment-1116792231
Hopefully it'll work for you too :)

**Comment by SenzelXPH** [comment]
Thanks, I wouldn't have guessed that myself.
