### ISSUE TITLE
[BUG] Child window move

### ISSUE THREAD

**Issue by PierrePharel** [LibreSprite/LibreSprite#38]
When i try to move child window, like window we get after press help > about button stranges recurring black outlines are draw and the moving of window is slow or  slow down.
And I tried to re-install and the same result is samething 

LibreSprite : v1.0-dev
System : Linux Mint 19.3

**Comment by candreslobor** [comment]
> When i try to move child window, like window we get after press help > about button stranges recurring black outlines are draw and the moving of window is slow or slow down.
> And I tried to re-install and the same result is samething
> 
> LibreSprite : v1.0-dev
> System : Linux Mint 19.3

i'm having the same problem

**Comment by PierrePharel** [comment]
And nobody for respond at our request...

**Comment by CodeMouse92** [comment]
Don't take it personally. :) The README says this is unmaintained. I'm seriously thinking about forking it and picking up maintenance, but I have to consider a few things first.

**Comment by jjhaggar** [comment]
MintStudios also stated a month ago that they wanted to maintain this project
https://github.com/LibreSprite/LibreSprite/issues/40

It would be great if you two could pick up maintenance and reactivate the project! :)

**Comment by MintStudios** [comment]
Hello! I'm pretty sure that is something that doesn't have to do with your system. On my Windows 10 **and** MX Linux 19.1, this problem persists. I don't really know why, but it happens. If I find the reason of this, I'll try to fix it.

**Comment by MintStudios** [comment]
This is a stale issue. I'm going to close this for now, but feel free to open it. It's not just you, but for everyone, as far as I know.
