### ISSUE TITLE
Cannot open file from command line

### ISSUE THREAD

**Issue by devnewton** [LibreSprite/LibreSprite#380]
##### LibreSprite version

1.0

##### Describe the bug
Running libresprite with a file path as command line argument do not open the specified file.

##### To Reproduce
Run `libresprite somesprite.ase`.

##### Expected behaviour
The specified file should be opened.

##### OS/Hardware
- Operative System: Debian GNU/Linux 11
- CPU: amd64
-

**Comment by maujin111** [comment]
i tried  `./libresprite somesprite.ase` on macOS, on the bin folder where the binary is located and works fine. Anyone can confirm if it works on linux or windows

**Comment by RamenSlayer** [comment]
Is the file perhaps on another drive with the mount point above home? I had such an issue on Manjaro using flatpak. If that's the case, building from source fixes the problem.

**Comment by felipemanga** [comment]
Closing since this seems to be an issue with that specific (flatpak?) build and no further information was provided after a year.

**Comment by devnewton** [comment]
The bug appears with the appimage version.

**Comment by devnewton** [comment]
I've mounted the appimage, the AppRun script does not pass argument to libresprite:

```
#!/bin/sh

PATH="$(dirname "$(readlink -f "${0}")")"
EXEC="${PATH}/usr/bin/libresprite"
exec "${EXEC}"
```

Solution : use `exec "${EXEC}"`
