### ISSUE TITLE
Cannot install themes

### ISSUE THREAD

**Issue by technicolorcoffee** [LibreSprite/LibreSprite#386]
##### LibreSprite version
```
Libresprite 1.0-dev
```

##### Describe the bug
Installed the latest appimage from the releases page, and I wanted to install a theme but when I open up the preferences menu and go to the themes section, it says it cannot open the folder. The appimage is installed on my downloads folder, while the LibreSprite files have been installed on my home/config folder. I have tried everything I can think of - tweaked my permission settings, rearranged where the files were located, no dice.

##### To Reproduce
Open up the latest version of LibreSprite, and do everything I did as explained in the bug section

##### Expected behaviour
Obviously LibreSprite should be able to access the config folder, or more precisely, should be able to access the skins folder within that

##### OS/Hardware
- Operative System: Ubuntu 20.04
- CPU: x86-64
- GPU: N/A

**Comment by maujin111** [comment]
A workaround can be to copy the themes and paste them on the home/.config/libresprite/data/skins folder, then you can access the themes on the app. I just tried it and it works. There is a problem with the appimage permissions
