### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by candreslobor** [LibreSprite/LibreSprite#39]
### Describe your bug report or feature request here
when i run the libreSprite program downloaded from flathub my cpu reaches 50% of usage, there is any way to solve it? 

### LibreSprite and System version

* LibreSprite (current 2020/03/10):
* System (Zorin OS linux debian/ubuntu based):

**Comment by MintStudios** [comment]
@candreslobor do you have a 32 bit architecture? Because I know from experience that libresprite hates 32 bit.

**Comment by candreslobor** [comment]
no, i'm on 64 bits

**Comment by MintStudios** [comment]
Hmm. This must be because of the flatpack, which is terrible. All I know is that either it's the 32 bit or the flatpack.

**Comment by candreslobor** [comment]
so, where can i download libresprite?

**Comment by MintStudios** [comment]
@candreslobor sometime, we will be making debian packages and other different packages for other distros sometime in the near future. Try to compile libresprite, and don't use the flathub, because it's terrible.

(If you compile correctly, please close this issue.)
