### ISSUE TITLE
List of feature differences with asesprite

### ISSUE THREAD

**Issue by Miepee** [LibreSprite/LibreSprite#391]
Currently there is no public list whatsoever detailing a better difference between Asesprite and Libresprite. 
I want to recommend Libresprite to more people, but currently they all just use Asesprite anyway because it's upstream and they don't know whether the "2016 fork" has caught up with all the features from recent releases.

Listing what features are exactly missing would also help potential contributors.

EDIT: I just found out that libresprite dotto is a thing. And while it does have a feature roadmap, a seperate comparison with asesprite would also be neat.

**Comment by felipemanga** [comment]
While this does have its uses, it's basically asking someone to keep copy+pasting Aseprite's changelog every time it gets updated.  Personally, I'd rather not.

**Comment by jjhaggar** [comment]
I do agree with felipemanga. I think it's much better just listing all the features that LibreSprite already has (which are **a lot** actually, and probably more than enough for most people).
