### ISSUE TITLE
Crash when forcing fullscreen and unfocusing

### ISSUE THREAD

**Issue by 00001H** [LibreSprite/LibreSprite#393]
##### LibreSprite version

```
1.2-973d0e3d-SDL
```

##### Describe the bug

I used Fullscreenizer to force-borderless-fullscreen the program, then unfocused it, and it crashed.

##### To Reproduce

Use Fullscreenizer to borderless-fullscreenize the program

Click into another program

Crash

##### Expected behaviour

No crash

##### OS/Hardware
- Operating<typo> System: Windows 10 22H2
- CPU: Intel Core i5-1135G7
- GPU: 

##### Additional context  

[LibreSprite-crash-1.2-973d0e3d-SDL.dmp.zip](https://github.com/LibreSprite/LibreSprite/files/10767785/LibreSprite-crash-1.2-973d0e3d-SDL.dmp.zip)

**Comment by 00001H** [comment]
Note: This bug is not consistent, try multiple times across program restarts.

**Comment by felipemanga** [comment]
This has probably been fixed by now, especially since there is now a built-in way to go into borderless fullscreen (View -> Toggle Fullscreen). 
Closing, but feel free to re-open if you find crashes when enabling fullscreen in a recent build (1.1-dev, as of now).
