### ISSUE TITLE
Would like to be the maintainer of LibreSprite

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite#40]
Hello, I am Mint Studios.
I enjoy open source projects like Godot. I would like to become the maintainer of this project.

My first act as a maintainer would be making a proper website, and make compiling this much, much easier. Adding new features is not in my plan. *Yet*.

I hope this happens.

@Calinou
@akien-mga

Seems to me, y'all were the last people to maintain this project.

**Comment by jjhaggar** [comment]
Hi @MintStudios :D

I am so glad that somebody finally made a step forward and volunteer for maintaining this repository! I would have loved to offer myself for the job, but I am not even able to build the project ^^U

I would like to assist you if possible, so if you need some help please tell me (for example, I could help by translating the new website into Spanish).

**Comment by MintStudios** [comment]
@jjhaggar 
I've compiled on linux, but am unsure how to open a file. Editing my project plans to this:

>Compile this piece of heart breaking code into actual executables, so people are not confused every step of the way.

**Comment by MintStudios** [comment]
I plan to compile on windows, which will hopefully be a success.

**Comment by MintStudios** [comment]
@jjhaggar I think I'll go ahead and make a discord server for this project, to act as some kind of social media.

**Comment by Wuzzy2** [comment]
As Discord is a proprietary software / a closed system, depending on Discord for communication would exclude all people who insist on free software.
Given that LibreSprite's main “selling point” is that it's free software (as opposed to proprietary), I think it's highly relevant what development tools you use.

**Comment by MintStudios** [comment]
Well, @Wuzzy2  , Godot Engine uses discord for interaction between users. I don't think discord will be used mainly for development, it's just a place where people can interact, talk about it, and get help. (Including non-developers/contributors.)

**Comment by jjhaggar** [comment]
I'm not a big fan of Discord myself, but I also think that creating a Discord server would be a great idea :)

**Comment by MintStudios** [comment]
Btw, anyone who is reading this, I am ready to take on the role. I've sent a message to @Calinou and @akien-mga on discord, but they haven't responded yet. I'll be patiently waiting 😆.

**Comment by MintStudios** [comment]
@jjhaggar do you use windows? If so, could you try this out:
(https://anonfile.com/f53cL4p4o7/LibreSpriteWin_exe)

**Comment by jjhaggar** [comment]
> 
> 
> @jjhaggar do you use windows? If so, could you try this out:
> (https://anonfile.com/f53cL4p4o7/LibreSpriteWin_exe)

I've just tried it and it works perfectly! :D

**Comment by Wuzzy2** [comment]
PS: I'm really hyped right now to see this project being revived. :-)

**Comment by MintStudios** [comment]
Yes!
That was really easy to do.

**Comment by MintStudios** [comment]
If y'all wanna join, https://discord.gg/5nX7txP
This is the discord server I made, which is unofficial currently.

**Comment by cosarara** [comment]
There seems to be activity at https://bitbucket.org/veritaware/libresprite/src/develop/
It's probably worth checking it out, and maybe get in touch with them.

**Comment by candreslobor** [comment]
Sounds interesting, what kind of people are you looking for?

**Comment by akien-mga** [comment]
Sorry for the late answer - maintaining Godot Engine doesn't leave me much room for other FOSS projects that may need attention.

I'm happy to add more maintainers to the GitHub org and see development restart, and I think it's a good initiative to open a Discord server to gather interested users in one place.

@MintStudios Are you still interested and motivated to help maintain LibreSprite in the foreseeable future?

Are there other candidates to co-maintain this project? To let the project thrive, having a single person "adopt" the project as sole maintainer is in my experience not optimal, as no peer review would really happen. While I'd probably stay as co-admin of the @LibreSprite org for the time being, I don't plan to have much time to do anything in the project, so I'd like to see at least 2-3 co-maintainers ready to get some work done and collaborate with each other.

**Comment by Ev1lbl0w** [comment]
I can help with organization and workflow, but since I started working on another project now, I have no time to learn the backends used and codebase to implement features. So I can help very little in terms of new features and bug-fixing, but for code review and style, I can help.

**Comment by MintStudios** [comment]
I think we could create linux packages and such, and compile binaries, and protect this code from bitrot. I don't think we should focus on developing new features unless they are critical.

**Comment by PerryHugh** [comment]
I am also interested in becoming a project maintainer. I sent an email to @akien-mga via his godotengine address.

@MintStudios are you still interested in doing this? Co-maintaining could really be beneficial and might be enough to kick this project into the spotlight.

**Comment by MintStudios** [comment]
Yes!

**Comment by PerryHugh** [comment]
Fantastic, this is going to be so much more efficient. Now, I know you created a Discord for the project, but I honestly feel an IRC channel is better for our purposes. It doesn't require sign up or non free software to access, and it is the de facto standard for open source projects. People will be much more inclined to talk if we keep the barrier for entry as low as possible.

In that spirit, I have made a FreeNode channel for us, accessible at [#LibreSprite](https://webchat.freenode.net/#LibreSprite). If you haven't used IRC before, that link will take you to an in-browser client. I'm in there, so pop on over and say hello!

**Comment by akien-mga** [comment]
Alright, I created a @LibeSprite/maintainers team and invited @MintStudios and @PerryHugh (+ @Calinou and I).

I tentatively enabled a requirement for **1** approved review before PRs can be merged to the `master` branch - we'll see how that works but I believe it's best to try to grow a team of co-contributors that cross-review each other's changes, instead of letting one of us make changes unilaterally.

**Comment by maujin111** [comment]
If you need help translating it to Spanish i would love to offer my self for the job, cloud be the ṕrogram or the website, readme, whatever

**Comment by jjhaggar** [comment]
Same here, I can also help with Spanish localization. We could both work on the translation if you want, Mauricio :)

**Comment by PerryHugh** [comment]
That is fantastic, both of you. As we go forward and produce more documentation for developers and news entries, I will let you know.

**Comment by maujin111** [comment]
I'm in jjhaggar ,  let's do the software accesible for everyone

**Comment by MintStudios** [comment]
OK, since @PerryHugh created a FreeNode channel, the discord server should be terminated, as one channel of this project will be easier for everyone.

**Comment by Ev1lbl0w** [comment]
> OK, since @PerryHugh created a FreeNode channel, the discord server should be terminated, as one channel of this project will be easier for everyone.

I don't think this is a good idea, and @akien-mga said it best in my opinion:

> The former *(Discord)* is sadly proprietary but also quite popular in the gamedev world, and good to grow a community of users

Discord is much more appealing to end-users, for being mainstream and much more user-friendly than IRC; it's a great place for people of all experience levels to gather and share anything, and especially because this is a creative program/community by nature.

**Comment by maujin111** [comment]
I agree with the Discord Chanel idea. Maybe its not open but its not Microsoft's either hahaha

**Comment by maujin111** [comment]
I'm also a programe and have some experiencie with c++, i would Like to help in the devoment too

**Comment by PerryHugh** [comment]
Forcing people to sign up for a third party service to chat with developers for support is a scenario best avoided. With IRC you simply enter a nick and you are in, particularly with browser based clients like Kiwi (which the link automatically loads). Discord seems unreasonable to me because of this.

Discord is to chat as Reddit is to forums. It allows you to create an interwoven community and converse about relevant topics. These places are great for grand topics like pixel art, but IRC is a better fit for a program's support channel as we are answering quick questions, or taking feedback. In the future a forum would be better for long term development planning.

**Comment by jjhaggar** [comment]
I'm not a Discord fan at all, so I probably shouldn't be arguing in its favour XD But the option of using both IRC and Discord looks like the best option to give users several options and thus ease of contact with the rest of the community.

**Comment by PerryHugh** [comment]
I agree with @MintStudios, one channel is easier for everyone. It also streamlines support, everyone available to help is in one location. People bouncing around between two platforms has a noticeable impact when the community is so small (for example, IRC currently has 6 users, self included).

Of course, there isn't a brass here. If you want to maintain a Discord channel, go for it. Though I think it's best for everyone if we stick to one official channel, regardless of platform. My advocacy for IRC has been stated.

**Comment by maujin111** [comment]
Look i'm not familiar with irc actually i kinda Like its simplicity but i have two issues with it: no official app (mobile or desktop) and not keeping record of the messenges. I think in a developer level its important keep the old messenges for avoid conffusions. If is there way of do that that please let me know

**Comment by Calinou** [comment]
We could have a Discord server bridged with the IRC channel for those who want to use Discord. This would require running a bridging bot on a 24/7 server though.

**Comment by Ev1lbl0w** [comment]
> I think in a developer level its important keep the old messenges for avoid conffusions. If is there way of do that that please let me know

@maujin111 you can use [Riot.im](https://about.riot.im/) - it's a very professional and good looking Matrix client, and it also supports IRC. It also has a "Discord" feel to it, and mobile versions.

> We could have a Discord server bridged with the IRC channel for those who want to use Discord. This would require running a bridging bot on a 24/7 server though.

@Calinou true, but I think that would kinda defeat the purpose of having two platforms then :stuck_out_tongue:
I think we can do something similar to Godot: having an IRC channels for development discussion and more professional talk, and Discord for the whole community for less technical talk about the project, such as art showcasing, asking for help or tips, etc...

**Comment by PerryHugh** [comment]
@maujin111 The purpose in IRC doesn't require logging as long term development discourse really should be decided on a more permanent basis such as a forum post or issue.

**Comment by maujin111** [comment]
@PerryHugh I agree with you, we could have tree channels, A IRC for technical technical purposes such a development, a website for news, realizes, blogs, forum, etc... and a discord server for the community for them to interact with each other, people use discord and are already familiar with it. we have to make communication channels accessible to everyone in the easiest way

**Comment by MintStudios** [comment]
I will close this, because of the size of thread.

**Comment by nanoslayer** [comment]
I'd also like to help out with maintaining LibreSprite. My main goal is to improve the experience for Linux users and distributions. This includes unbundling various dependencies and fixing some issues that LibreSprite has when it is compiled with musl libc.
