### ISSUE TITLE
File Not Found when dragging files from mounted media.

### ISSUE THREAD

**Issue by 4127157** [LibreSprite/LibreSprite#407]
##### LibreSprite version

```
LibreSprite v1.0
```

##### Describe the bug

"File Not Found" error when dragging files into libresprite from an external hard drive or a symlinked directory to the mounted drive. 
##### To Reproduce

Mount an external drive. Browse the inbuilt file browser in LibreSprite and the location does not appear. The same behavior is present if you create a symlink to this location in a discoverable folder. 
##### Expected behaviour

The program is able to treat any symlinks or mounted drives just the same as any other. I'm able to drop files in it from any location. 
##### OS/Hardware
- Operative System: Fedora 37
- CPU: Intel i5 6500
- GPU: 

##### Screenshots  

![image](https://github.com/LibreSprite/LibreSprite/assets/89254856/56a2e5e9-d26d-48cc-b402-7e94a25f7387)

##### Additional context  

The screenshot is after attempting to drag a file in LibreSprite. I also tried enabling the experimental feature of using the native file dialog but that did not have any affect.

**Comment by maujin111** [comment]
Great to know that it works now, it should be and issue with the flatpak permissions.

**Comment by felipemanga** [comment]
This is a flatpak feature: https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory
