### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by OxyZin** [LibreSprite/LibreSprite#409]

**Comment by OxyZin** [comment]
[LibreSprite-crash-1.2-973d0e3d-SDL.txt](https://github.com/LibreSprite/LibreSprite/files/11926616/LibreSprite-crash-1.2-973d0e3d-SDL.txt)

rename it to .DMP

**Comment by felipemanga** [comment]
Update to v1.0. We can't do much about pre-release crashes at this point.
