### ISSUE TITLE
Musl KISS linux allegro segmentation fault

### ISSUE THREAD

**Issue by muevoid** [LibreSprite/LibreSprite#41]
Describe your bug report or feature request here

After compiling libresprite and running it I get a segmentation after the window quickly pops up telling of a segmentation fault.

LibreSprite 1.1.7

1.1.7
KISS Linux(musl libc)

**Comment by JamesK89** [comment]
What Linux kernel and hardware are you using? I tried this on a virtual machine Kubuntu (20.04, VirtualBox) with a chroot install of KISS Linux. I was able to successfully build and run LibreSprite within the KISS Linux environment. I did, however, get a segmentation fault when exiting LibreSprite but the application behaves normally otherwise.

**Comment by muevoid** [comment]
I'm on the latest stable kernel. Hardware I am on a system 76 darter pro 6. I havent tried in a while and have since re installed the distro so I may try again in a few.

**Comment by muevoid** [comment]
Update: I have tried again and it launches fine now but segfaults when saving due to Allegro signal #11

**Comment by muevoid** [comment]
I think I know this issue I used gdb to find source of segfault it is thrd_detach function. I will look into patching this and if I do I will open a pull request.

**Comment by muevoid** [comment]
I fixed it however it is a pretty scuffed fix and i'm not sure the implications of it. I commented out the pthread_detach function. Since in posix instead of undefined behaviour like in glibc it segfaults. Then there is another issue that says cannot save "" files however that is easliy fixed by just touching the file u want to save to in terminal.

**Comment by JamesK89** [comment]
> Edit: Were you able to save files in the vm?

I get a core dump when I try saving a file.
I will need to investigate this later and see if I can get a stack trace but right now I'm kind of short on time.

```Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lockToWrite: Locked <2> to write
Document::lock: Locked <2> to write
Aborted (core dumped)```
