### ISSUE TITLE
What happened to 2022 commits?

### ISSUE THREAD

**Issue by veganaize** [LibreSprite/LibreSprite#412]
##### What's wrong with the code?
All commits from 2022 are gone?

##### How should it be improved?
Restore commits from 2022...  If it isn't too late?

##### Additional context  
For example, I committed this... https://github.com/LibreSprite/LibreSprite/pull/371/commits/3e44632f87a4f80e814f7ce2ae0deb0a10872c18

And the change (among how many others?) was apparently blasted from the repo.

**Comment by jn64** [comment]
Hi, I see your commit 3e44632 as part of squashed merge https://github.com/LibreSprite/LibreSprite/commit/57605c6cd9ccd2b0e230cd28f3d899062e3bbc65

in refactor branch https://github.com/LibreSprite/LibreSprite/commits/refactor

(I'm just passing by, I don't know the reason for it being in refactor branch but not master)

**Comment by felipemanga** [comment]
The repository was unstable so we rolled back and will be cherry-picking things back gradually once we know things are OK.

**Comment by veganaize** [comment]
Is anything being done to prevent this issue, moving forward?  (regression tests, pull reviews, etc.)

**Comment by felipemanga** [comment]
The missing commits have been restored, unless I've missed something unintentionally (in which case, feel free to open a new issue). 
Unfortunately we lack the resources for formal testing/reviewing at the moment. On the other hand, we're probably not going to try that refactor again.
