### ISSUE TITLE
Doesn't compile with -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by awisse** [LibreSprite/LibreSprite#413]
##### LibreSprite version

```
master - 6ffe8472194bf5d0
```

##### Describe the bug

Compilation stops here:

     [266/726] Building C object src/script/CMakeFiles/duktape.dir/__/__/third_party/duktape/duktape.c.o
     ninja: build stopped: subcommand failed.

##### To Reproduce

    cmake -G ninja -DCMAKE_BUILD_TYPE=Debug
    ninja libresprite

##### OS/Hardware
- Operating System: Linux Pop OS (Ubuntu 22.04)
- CPU: 12th Gen Intel(R) Core(TM) i7-12700H

##### Additional context  

Compiles with *Release* and *RelWithDebInfo*.

**Comment by maujin111** [comment]
The normal `cmake -G ninja && ninja libresprite` works?

**Comment by awisse** [comment]
Yes: *RelWithDebInfo* and *Release* both fully compile.
