### ISSUE TITLE
Can not be opened on Mac. Unverified application error.

### ISSUE THREAD

**Issue by tahamousavi** [LibreSprite/LibreSprite#419]
##### LibreSprite version
Version 1.0.0

##### Describe the bug
It cannot be opened because the developer cannot be verified.
<img width="372" alt="Screenshot 2023-10-02 at 13 04 00" src="https://github.com/LibreSprite/LibreSprite/assets/10095460/bb3cab4a-998e-414f-8994-f4b9e1d8d211">

##### To Reproduce
Install it on the MacBook Air lastest Mac OS version

##### OS/Hardware
MacBook Air M2
Mac OS 14.0

**Comment by codeoutin** [comment]
You can go to System Settings > Security, scroll all the way down and click "Open anyway". But yeah maybe the devs can also fix that for future versions. Running great on macOS 14.0 so far

**Comment by orowith2os** [comment]
This is unlikely to be solvable, unless someone is willing to fork out some money for the LibreSprite developers to pay Apple for a license so it isn't flagged on macOS. You will likely also encounter the same issue with many other small apps as well.

**Comment by felipemanga** [comment]
There are currently no plans on paying Apple to get rid of their nagging pop-up.
