### ISSUE TITLE
How do export an animation into seperate png's

### ISSUE THREAD

**Issue by ClappuBlappu** [LibreSprite/LibreSprite#423]
Does anybody know how to export an animation's frames into seperate pngs instead of a sprite sheet. I know this isn't really a bug report and more of a question, but I'm really stumped on this.

**Comment by jjhaggar** [comment]
You can export a png sequence by clicking on "File > Save copy as" and naming the file something like this "ImageSequenceName 01.png", Libresprite will ask you if you want to export the animation in separated files, you click on "Agree" and that's it.
![image](https://github.com/LibreSprite/LibreSprite/assets/4078392/84153ef0-4bb0-428a-a986-1d6750d7a80e)

But it's is better if you ask future questions in LibreSprite's Discord channel https://discord.gg/95gbyU5
