### ISSUE TITLE
The "Use native mouse cursor" option doesn't appear to function.

### ISSUE THREAD

**Issue by sergeirocks100** [LibreSprite/LibreSprite#424]
##### LibreSprite version

```
"LibreSprite v1.2-973d0e3d-SDL"
```

##### Describe the bug

The "Use native mouse cursor" option doesn't appear to function.

##### To Reproduce

1. Check the option under the "Cursors" tab in the preferences.
2. The cursor won't change from the built-in cursor, even if you restart.

##### Expected behaviour

I expected it to use the Windows cursor set in the program, instead of the built-in one.
##### OS/Hardware
- Operative System: WIndows 10 Pro 1909
- CPU: Intel Core i7 4600U
- GPU: 

##### Screenshots  

![Screenshot_98](https://github.com/LibreSprite/LibreSprite/assets/31294280/1077081d-a4dd-458a-b3ae-f4d9c29e4ea3)
As you can see here, even though i have the option enabled, the built-in cursor is still showing up. 

While i can't convey this information through an image, and my ThinkPad is probably going to light itself on fire if i try to record a video, i did apply the option, and i did restart the program to make sure it actually applied.

##### Additional context  

I'm using the x86-64 build provided under the 1.0 release tag, if it matters.

**Comment by felipemanga** [comment]
The SDL2 backend we are using now does not support native mouse cursors.
We should probably remove the menu option.
