### ISSUE TITLE
LibreSprite crashes when attempting to insert text

### ISSUE THREAD

**Issue by osb21313** [LibreSprite/LibreSprite#427]
##### LibreSprite version
```
LibreSprite 1.2-973d0e3d-SDL
```

##### Describe the bug
I am trying to insert some text, although LibreSprite just crashes.

##### To Reproduce
Edit > Insert Text (T)

##### Expected behavior
I was thinking that the Insert Text menu would pop up, although it didn't.

##### OS/Hardware
- Operating
 System: Windows 11
- CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

Crash file:
[LibreSprite-crash-1.2-973d0e3d-SDL.dmp](https://github.com/LibreSprite/LibreSprite/files/13405421/LibreSprite-crash-1.2-973d0e3d-SDL.dmp)

**Comment by felipemanga** [comment]
Please update to a supported version (1.0 release) or make a build from the latest master branch. 
"1.2-...-SDL" builds are old/unstable/testing builds from before the 1.0 release.

**Comment by osb21313** [comment]
> Please update to a supported version (1.0 release) or make a build from the latest master branch. "1.2-...-SDL" builds are old/unstable/testing builds from before the 1.0 release.

I downloaded 1.0 although I am checking the version and it is the old version.
