### ISSUE TITLE
Cash when I right-click on a layer

### ISSUE THREAD

**Issue by Doodlinka** [LibreSprite/LibreSprite#429]
##### LibreSprite version
```
1.2-973d0e3d-SDL
```

##### Describe the bug
Sometimes, when I right-click on a layer, both the name/mode opacity and the new/properties/duplicate menu open. Everything but the name/properties menu becomes unresponsive, and when I close it or go into windowed mode (or maybe after enough time?) the program crashes/

##### To Reproduce
Right-click on a layer in the layer list a bunch. I think it happens when I right-click on the layer name, but I wasn't able to reproduce it consistently.

##### Expected behaviour
I expect the program to open only one of the menus, not become unresponsive, and not crash.

##### OS/Hardware
- Operative System: Windows 10
- CPU: AMD Ryzen 7 1700 Eight-Core Processor 3.00 GHz

##### Additional context  
[LibreSprite-crash-1.2-973d0e3d-SDL - Copy.dmp](https://github.com/LibreSprite/LibreSprite/files/13543351/LibreSprite-crash-1.2-973d0e3d-SDL.-.Copy.dmp)
[LibreSprite-crash-1.2-973d0e3d-SDL copy.dmp](https://github.com/LibreSprite/LibreSprite/files/13543352/LibreSprite-crash-1.2-973d0e3d-SDL.copy.dmp)
[LibreSprite-crash-1.2-973d0e3d-SDL four.dmp](https://github.com/LibreSprite/LibreSprite/files/13543353/LibreSprite-crash-1.2-973d0e3d-SDL.four.dmp)
[LibreSprite-crash-1.2-973d0e3d-SDL.dmp](https://github.com/LibreSprite/LibreSprite/files/13543354/LibreSprite-crash-1.2-973d0e3d-SDL.dmp)

**Comment by felipemanga** [comment]
Please try downloading the github action build and see if the issue has been fixed.
