### ISSUE TITLE
Android port lag (at the canvas)

### ISSUE THREAD

**Issue by RebornOfc** [LibreSprite/LibreSprite#430]
(I know the android port was released last week and is on early development)

Issue: The fps is great on the beginning as you can see by the cursor, but at the moment I open the canvas and start dragging the cursor around you can see some frames missing (its near the end of the video)

https://www.veed.io/view/ee1df284-83b2-4e9d-abed-f5548ead3f81?sharingWidget=true&panel=

Device: Moto g54, android 13, 4GB ram, Mediatek dimensity 7020

**Comment by felipemanga** [comment]
These are debug builds, compiled with compiler optimizations turned off. 
I'd expect performance to be much better when we have an actual release build.
