### ISSUE TITLE
Scripts not being recognized in .config folder. 

### ISSUE THREAD

**Issue by MetalMaxMX** [LibreSprite/LibreSprite#431]
##### LibreSprite version

```
2b183dec0cecc4e78c9a918c63441112e4acba41
```

##### Describe the bug

If you have any scripts on .config/libresprite/scripts, it won't recognize them as of latest master. This is a regression as a few commits ago this behavior was not happening
##### To Reproduce

If home/.config/libresprite/scripts has any scripts, then check if they appear on LibreSprite, likely won't. 
##### Expected behaviour

The scripts appear and are being recognized by LibreSprite from that default folder (instead of simply the scripts from usr/local/share
##### OS/Hardware
- Operative System: Debian 11

##### Additional context  

I used https://github.com/firstmiddlelast/libresprite-extensions as the testbed and was able to verify the bug.

**Comment by felipemanga** [comment]
Thanks for the heads up, it should be fixed now.

**Comment by MetalMaxMX** [comment]
Hello, yes! It works properly now on my end! I'll mark the issue as solved.
