### ISSUE TITLE
Native cursor setting not takes in account

### ISSUE THREAD

**Issue by Natahan-Tatan** [LibreSprite/LibreSprite#435]
##### LibreSprite version
1.0-dev commit e3c4506

##### Describe the bug
The cursor still the app one even when the settings "Use native cursor" is checked.

##### To Reproduce
Just go to Preferences, check the setting and apply.

##### Expected behaviour
Replace the specific cursor by the native one.

##### OS/Hardware
- Operative System: Ubuntu 22.04.1 | kernel 6.2.0-39-generic
- CPU: AMD Ryzen 7 7840U
- GPU: Radeaon 780M Graphics (integrated graphics)

##### Screenshots  
![image](https://github.com/LibreSprite/LibreSprite/assets/88054177/2174c4d5-c7d9-426a-a455-d1659f5e3ea8)

##### Additional context  
- I use the released **libresprite-Linux--x86_64** Appimage.
- I use KDE with Plasma desktop version 5.24.7
- Display server is X11

**Comment by felipemanga** [comment]
This isn't really a bug, it's just not supported on the current backend (native mouse cursors were a feature of the long-gone Skia backend).
I remember implementing it back then, and it was terrible because SDL2 doesn't provide all the necessary cursors.
I'll give it another go.

**Comment by felipemanga** [comment]
Implemented, but what cursors appear and which ones fallback to the non-native cursor is going to vary a lot from one OS and SDL version to the next. In the case of Android, this actually makes the cursor disappear entirely, which is great for pen/touch, but I imagine will be terrible if you have an actual mouse plugged in.
