### ISSUE TITLE
LibreSprite website.

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite#44]
I've created a small web page at https://LibreSprite.github.io that has a button for a windows installer. I'm not very good at making cool-looking websites, so I've just created a repo for the website, and people can improve it.

**Comment by PerryHugh** [comment]
I think this will work for now, but pretty quickly I want to move to properly hosted website so we can maintain a forum instead of using issues for general discussion and updates.

Hopefully we can find the person who purchases libresprite.org.

**Comment by jjhaggar** [comment]
That's great, thank you very much MintStudios! :D

About the other thing, I've been searching a bit, and maybe we could try to contact the person who registered the domain using the info here https://libresprite.org.cutestat.com/
I'm not pretty sure that it'll work, but it looks like there is an email -> jamesk89 at gmail.com 

Would you like to try to contact him, PerryHug?

**Comment by PerryHugh** [comment]
I'll try to get in touch @jjhaggar, though I too am doubtful.

**Comment by maujin111** [comment]
just made a pull request to improve a little bit the website, if you like i could be the manteiner

**Comment by MintStudios** [comment]
@maujin111 I made you a maintainer.

@akien-mga Are you OK with this?

**Comment by maujin111** [comment]
@MintStudios Thank you I Will do my Best

**Comment by PerryHugh** [comment]
Awesome, it needs a maintainer and we already have someone step up for it.

**Comment by PerryHugh** [comment]
@maujin111 @MintStudios
James Kelly responded, he wants to know what kind of forum software we want and he can help set it up. I am personally thinking phpBB with a blog roll (Wordpress?) for news.

But I want to hear the community's take on it before I respond. I have also linked him to this post so he can weigh in if he likes.

**Comment by jjhaggar** [comment]
Oh, that's great news @PerryHugh :D 
phpBB + Wordpress sounds fine to me.

**Comment by maujin111** [comment]
That's amazing, phpbb works for me too

**Comment by Shoozza** [comment]
The Aseprite Website uses Discourse for the forum: https://github.com/discourse/discourse

**Comment by maujin111** [comment]
Any news about the domain?

**Comment by PerryHugh** [comment]
Not yet, sent him a message but when he gets back I'll let everyone know for sure if he doesn't come to this issue and post himself.

**Comment by maujin111** [comment]
@MintStudios  I suggest closing this thread, any issues related to the website should be discussed in the website repository
