### ISSUE TITLE
not letting me save as flc or fli

### ISSUE THREAD

**Issue by dax0lotl** [LibreSprite/LibreSprite#444]
##### LibreSprite version

```
v1.0-dev
```

##### Describe the bug

whenever i try to save my animation as an flc or fli file, it simply says it cannot export information like RGB format and Alpha channels, and then says "would you like to proceed with .flc/.fli format?" But then it doesn't give me the option to proceed, it just gives me a close button
##### To Reproduce

change file type to .flc/.fli and try to save
##### Expected behaviour

i expected to have a proceed button along with a close button
##### OS/Hardware
- Operative System: Kubuntu 22.04
- CPU: 4 x Intel Celeron N4120 CPU @ 1.10GHz

**Comment by maujin111** [comment]
Resolve on v1.1
