### ISSUE TITLE
Add installer source code/migrate to non commercial free installer generator

### ISSUE THREAD

**Issue by Shoozza** [LibreSprite/LibreSprite#48]
Hello, does someone know where the source code for the windows installer can be found?

I noticed that the installer was generated with installsimple, a commercial product.
Would be be possible to use something freely available instead?

Some possible options are:
* Innosetup: https://jrsoftware.org/isinfo.php
* NSIS: https://nsis.sourceforge.io/Download
* WiX Toolset: https://wixtoolset.org/

### LibreSprite and System version

* LibreSprite (latest):
* System (Windows):

**Comment by maujin111** [comment]
Innosetup it's free but not open source, even have some restrictions on distribution and use; https://jrsoftware.org/files/is/license.txt
I'm looking for some alternatives for our windows user friends, but i don't have any machine running windows but a windows installer it's a priority.

**Comment by akien-mga** [comment]
I know @Calinou has some experience with that.

**Comment by Calinou** [comment]
@maujin111 Inno Setup *is* open source. That license is similar (but not identical) to the [Zlib license](https://opensource.org/licenses/Zlib) which is FSF- and OSI-approved.

**Comment by maujin111** [comment]
Oooh i see, so that could be an option

**Comment by akien-mga** [comment]
I put the current Windows installer build in a `_tmp` tag, which is meant to be removed once we have a proper documented pipeline to generate builds from each commit like done with the Linux AppImage:
https://github.com/LibreSprite/LibreSprite/releases/tag/_tmp

**Comment by Shoozza** [comment]
I'm working on the innosetup installer.

**Comment by MintStudios** [comment]
I'll close this, as Innosetup is working, and it'll be merged soon.
