### ISSUE TITLE
Mac M2 Sonoma - LibreSprite prevents display sleep

### ISSUE THREAD

**Issue by scomx** [LibreSprite/LibreSprite#498]
##### LibreSprite version

```
1.0
```

##### Describe the bug
LibreSprite prevents MacOS display from sleeping.

##### To Reproduce
Run LibreSprite, display will remain on forever unless app is closed.

##### Expected behaviour
App should not prevent display from going to sleep.

##### OS/Hardware
- Operative System: MacOS Sonoma 14.6.1
- CPU: Apple M2

##### Output from pmset -g confirms the issue (displaysleep setting):
```
❯ pmset -g
System-wide power settings:
Currently in use:
 standby              0
 Sleep On Power Button 1
 autorestart          0
 powernap             1
 networkoversleep     0
 disksleep            10
 sleep                1 (sleep prevented by powerd, bluetoothd, sharingd)
 ttyskeepawake        1
 displaysleep         10 (display sleep prevented by libresprite)
 tcpkeepalive         1
 lowpowermode         0
 womp                 1 
```

**Comment by felipemanga** [comment]
Thanks for the heads-up (and the pmset -g command). Turns out this was an unintended feature.
