### ISSUE TITLE
Custom file extension

### ISSUE THREAD

**Issue by Ev1lbl0w** [LibreSprite/LibreSprite#50]
LibreSprite still uses the `.ase` [format](https://github.com/LibreSprite/LibreSprite/blob/master/docs/files/ase.txt) from the original project; this can create problems, as those files might be incompatible with our version.

I propose changing the project and specification to use `.lse`; a quick Google search shows that it's not linked to a popular program, so it should be safe to use.

We could also make our program compatible with original `.ase` files, but we have to investigate if we have the permission to do so.

**Comment by PerryHugh** [comment]
The original ASE format was released GPL v2, but either way adding interoperability would be legal (look at LibreOffice with MS Word documents). I would suggest always supporting ASE format, including added additions. This allows a more smooth transfer of users to LibreSprite as time goes on.

We can create a new format if necessary, but changing the name of everything to match isn't necessarily the goal. This history has an irrefutable history with Aseprite and that shouldn't be hidden. If people think it is more justified to make the purchase of his product as opposed to using an open source variant, more power to them. Hiding this connection I think makes us look bad and may turn some people off of open source if they get an immoral inkling.

**Comment by Ev1lbl0w** [comment]
> We can create a new format if necessary, but changing the name of everything to match isn't necessarily the goal. This project has an irrefutable history with Aseprite and that shouldn't be hidden. If people think it is more justified to make the purchase of his product as opposed to using an open source variant, more power to them. Hiding this connection I think makes us look bad and may turn some people off of open source if they get an immoral inkling.

The purpose of this is not to "hide" the connections to Aseprite; it's to ensure that if there are incompatibilities between the two programs, it's more obvious to the user.

Looking at the MS Word and LibreOffice example: LibreOffice uses it's format `.odf`, but allows to edit and save to the popular `.docx`. There might be certain features, however, exclusive to LibreOffice, that can only be preserved by using the `.odf` format. LibreOffice supporting the two formats gets the best of both worlds: it allows people to work with the program with the best `.odf` format, but still allow them to work with the more popular `.docx`. *(I know that the new MS Office can now work with `.odf` aswell, but for the sake of argument, suppose it still couldn't)*

As a matter of fact, I tried creating a simple sprite on Aseprite, and them opening it up on LibreSprite. Although it loaded fine, it had errors reading the file, so the format did change.

I agree it's important for LibreSprite to work with the Aseprite format; however, if there are new features exclusive to our version, then the saved `.ase` file might be imcompatible with Aseprite; hence the suggestion for a new file extension.

**Comment by maujin111** [comment]
i understand the need to create an own identity for the software but if it's not broken, don't fix it

**Comment by PerryHugh** [comment]
I agree that if we add save altering features that are not supported by Aseprite than we would have to make an extended or unique format. The likelihood of this is pretty slim in the short term, though nothing is impossible.

I think our first format related goal should be to get interoperability with the current ASE file format.

**Comment by MintStudios** [comment]
I am closing this since this has been settled.
