### ISSUE TITLE
deadlock with certain strings as layer names

### ISSUE THREAD

**Issue by CrispyPin** [LibreSprite/LibreSprite#503]
##### LibreSprite version

```
1.1-dev
```

##### Describe the bug

Certain strings, seemingly that contain a colon, cause LibreSprite to freeze up indefinitely, using 100% of one cpu core.

The bug still exists on the latest commit on the master branch (`a678ddf8952a8be435bbd90da5071ab83aaf6183`)

##### To Reproduce

Rename a layer to one of the known broken strings, then hover the mouse over the name.

Known broken strings:
- `train :3`
- `lines :`
- `a   :` (that's 3 spaces)

##### Expected behaviour

No freeze

##### OS/Hardware
- Operative System: Arch Linux
- CPU: AMD Ryzen 5 5600X

**Comment by CrispyPin** [comment]
after more testing it seems like any string at least 5 characters long containing ` :` anywhere causes it

**Comment by jjhaggar** [comment]
It happens also on Windows 10 (I tried renaming a layer to "train :3"). 
![image](https://github.com/user-attachments/assets/3cd5383c-7e63-485c-8dcc-b0a02532fd22)

**Comment by CrispyPin** [comment]
It's getting stuck in `IndicatorsGeneration::add` (`src/app/ui/status_bar.cpp:279`), I can't tell exactly what the intent here is but it seems like it's supposed to only display the part of the layer name before "` :`" in the status bar. This code was added in 2016 in commit [87ef48b50b](https://github.com/LibreSprite/LibreSprite/commit/87ef48b50b). The function is unchanged since then so the bug likely existed the whole time.

**Comment by CrispyPin** [comment]
Apparently this does not break and is presumably what it's supposed to do? The `" :: "` is just cut from the status bar.
![image](https://github.com/user-attachments/assets/ae73e5e4-95bb-4c99-9912-801aaa2a4e37)
(cursor not in screenshot, but hovering the layer name)

**Comment by felipemanga** [comment]
I've found the bug: it crashes when trying to parse an icon in the layer name. If you want to see what it's supposed to do, try `bacon :rgb: burger` and it will add the rgb icon to the status bar at the bottom.

**Comment by felipemanga** [comment]
Issue seems to be fixed, feel free to open a new one if that is not the case.
