### ISSUE TITLE
Libresprite Logo

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite#51]
I don't think I have permission to change the logo for the organization. @akien-mga or @Calinou , could you maybe change the profile picture the the libresprite logo? The github default looks unprofessional.

**Comment by akien-mga** [comment]
I fixed this 8 hours ago already.

**Comment by Calinou** [comment]
I can see the new one:

![image](https://user-images.githubusercontent.com/180032/86392800-52e6d100-bc9c-11ea-88d1-e8e205e34214.png)

You may have to clear your browser's cache to see it.

**Comment by MintStudios** [comment]
Ah, yes, I see it now.
