### ISSUE TITLE
Installers Version

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/LibreSprite#61]
It would be a good idea to name the installers for the current version. Whether alpha, beta or stable. Example: libresprite_V1_0_beta.exe. To let the user know which version they are downloading. Regardless of the build.

**Comment by MintStudios** [comment]
We don't need to add underscores for the versioning. You could just do libresprite_v1.0_beta.exe.

**Comment by maujin111** [comment]
since a name is already established for the versions "libresprite_v1.0_beta.exe." i will close this
