### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/LibreSprite#62]
What are the minimum system requirements to run libresprite smoothly?

- Operating System
- Processor
- RAM
- OpenGL?
- vram?

**Comment by jjhaggar** [comment]
No idea at all :S

Should I try installing the current build in some old computers I have, or there is other methods to test this?

**Comment by Ev1lbl0w** [comment]
Well, these are the system requirements of Aseprite [on Steam](https://store.steampowered.com/app/431730/Aseprite/) *(for Windows)*:

```
OS: Windows Vista, 7, 8, or 10
Memory: 128 MB RAM
Storage: 40 MB available space
```

**Comment by maujin111** [comment]
Today i will try to run it on this laptops: 

AMD E1-2100 APU  1.GHz - 4Gb Ram- Radeon(TM) HD Graphics - ArchLinux XFCE

AMD E2-9000e APU 1,5 GHz to 2,0 GHz 1 Mb cache - 4Gb Ram - Graphics  Radeon R2 - Windows 10

Intel i5-5350H  3,50 GHz 4 Mb cache - 4Gb Ram - Intel Graphics - Windows 10

Intel i7-8750H  4,10 GHz cache 9Mb;  - 16Gb - Nvidia GT1600Ti - SSD - Manjaro XFCE

Intel Core i5 dual core to 1,6 GHz - 4Gb Ram  -Intel HD Graphics 6000 - SSD - MacOS X Catalina

**Comment by maujin111** [comment]
> Well, these are the system requirements of Aseprite [on Steam](https://store.steampowered.com/app/431730/Aseprite/) _(for Windows)_:
> 
> ```
> OS: Windows Vista, 7, 8, or 10
> Memory: 128 MB RAM
> Storage: 40 MB available space
> ```

128 Mb of ram and windows vista? that sounds a little crazy
the 128 Mb should be the amount of ram that the program consume

**Comment by maujin111** [comment]
I have tried in five machines using different operating system and hardware. the ram consumption whit at least one tab open is at least 10Mb whit 0% of stress even on 1Ghz Machines.

**Comment by maujin111** [comment]
@MintStudios we Should set a minimum hardaware requirement  and close this issue
