### ISSUE TITLE
Almost all option on help button doesnt work #13

### ISSUE THREAD

**Issue by AxelVarreira** [LibreSprite/LibreSprite#65]
Well, i was looking for the dark theme and when i was on the "help" button, just the readme and about option was working , i think is a simple issue, but an important feature

* LibreSprite: v1.0-Dev
* System: PopOs 20.04

**Comment by PerryHugh** [comment]
Thank you for creating an issue. This is indeed a problem and will require the creation of proper documentation for LibreSprite to be fixed. Ideally we will have a website with MediaWiki or something of the sort installed soon which will allow us to replace the links to Aseprite's documentation.

You can find the dark theme as well as installation instructions [here](https://github.com/maujin111/than_dark_theme_libresprite).

**Comment by Shoozza** [comment]
Currently the Help menu entries point to:

Readme -> https://github.com/LibreSprite/LibreSprite#readme
Quick Reference -> https://github.com/LibreSprite/LibreSprite/quickref/
Documentation -> https://github.com/LibreSprite/LibreSprite/docs/
Tutorial -> https://github.com/LibreSprite/LibreSprite/tutorial/
Release Notes -> https://github.com/LibreSprite/LibreSprite/release-notes/
Donate -> https://github.com/LibreSprite/LibreSprite/donate/

Of these only the Readme entry works.
