### ISSUE TITLE
Working on Spanish UI

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/LibreSprite#67]
I am currently working at the Spanish UI. I already have my LibreSprite compilation in Spanish but I was thinking of putting a welcome screen where the users can choose the language or put the option to change the language in preferences but for that I need to modify the base code and it will take some time.

What do you think, welcome screen or option in preferences?

![Captura realizada el 2020-07-07 07 36 15](https://user-images.githubusercontent.com/25780951/86783015-693ab700-c025-11ea-8b07-e5f1cf1eaa59.png)

**Comment by Ev1lbl0w** [comment]
I like the idea of a one-time welcome screen for general configs, like how Blender does:
![image](https://user-images.githubusercontent.com/6501975/86791320-53e37e00-c061-11ea-9afe-69709caab5b1.png)

But even with a welcome screen, there should be an option to change the language in the "Options" menu/screen anyways.

**Comment by jjhaggar** [comment]
Yes, using both the "welcome screen" and the "options menu" to choose language looks like the best option :)

**Comment by maujin111** [comment]
Yes, will work on that, but first i will try to put the option on the experimental section on preferences

**Comment by Ev1lbl0w** [comment]
Please do keep in mind that we still need to implement a proper localization system, to not only prevent the code from becoming a mess, but to also make it easier for other people to help with translation too.

It's likely you would need to redo your translation again when that happens, so please do keep that in mind.

**Comment by PerryHugh** [comment]
I agree, a first time welcome screen like Blender's sounds great. Thank you for working on translation @maujin111.

@Ev1lbl0w is absolutely correct though, eventually (preferably before translation is started honestly) we will need to draw strings from external files so the code can remain clean. The more languages we add now, the more difficult a task this becomes.

**Comment by maujin111** [comment]
I suggest closing this issue as it is duplicate of #49
