### ISSUE TITLE
MediaWiki for LibreSprite, closing issues.

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite#68]
As mentioned in #65 , we should create some proper documentation. I'll try to set this up, and will create the basis for it. I would think MediaWiki is ideal for this project, because it is open-source, and has that classic Wikipedia look and feel.

2., there are a lot of issues that should be closed. Issue 40 should be closed, as it doesn't have a purpose anymore. LibreSprite should make an effort to close stale and solved issues.

**Comment by maujin111** [comment]
Let us know when you set up the MediaWiki, i'm working on a "Know your WorkSpace" tutorial whit screenshots and everything, where it is explained what each tool is used for. I was thinking on putting it on the website on a new section. but a mediaWiki sounds fine to me too

**Comment by MintStudios** [comment]
@maujin111 can you look at your issues to see which ones you could close?

**Comment by maujin111** [comment]
> @maujin111 can you look at your issues to see which ones you could close?

@MintStudios Done

**Comment by PerryHugh** [comment]
That is great you're working on new documentation @maujin111. Getting a MediaWiki would be fantastic, though I still haven't heard back from James Kelly on the domain and whether or not he is willing to follow through on the offer of helping set up a forum. If that is the case, we would be able to host it on the official domyain. Either way we can transfer later if need be.

**Comment by PerryHugh** [comment]
James Kelly has provided us with a [website](http://www.libresprite.org), forum and MediaWiki included.

**Comment by MintStudios** [comment]
@PerryHugh how can we further develop the site? Is the source on github?

I see there is a news tab, but my question is how is that going to be used? (As in how do we create news and have it show up on the site.)

**Comment by PerryHugh** [comment]
This discussion should take place on the forum, not in an issue.

The News section can be updated by anyone with WordPress access, I figured we should all agree on an article to be posted to it from our sub-forum for General Infrastructure and for releases in the release development thread.

WordPress, MediaWiki, and PHPBB are open source projects, so you can look at them if you want, but there is no repository for our website like you're thinking. Anyone with access (all maintainers should have access, shoot me an email and I'll send the information over) can modify the whole website.

I just tweaked it to have a simple cohesive design that remains through transitioning to the forum. There can be more done of course. I don't think we should go overboard with web dev but if someone has an awesome idea, I think we should implement it.

MediaWiki can be edited by anyone, just create an account and add or modify some articles, this will house all of our documentation. I have already ported over two articles from markdown to it (very time consuming).

If you want to discuss further though, make a [thread](http://www.libresprite.org/forums/viewforum.php?f=13), as the issue of implementing MediaWiki is completed.
