### ISSUE TITLE
Window trails while moving windows other than main window.

### ISSUE THREAD

**Issue by yuyutsupoudel** [LibreSprite/LibreSprite#72]
A trail of window forms while moving window. It does not happens in main window but only on secondary window. like while moving "New File" and "Open File" 
[picture](https://user-images.githubusercontent.com/49397015/87944029-92942200-cabe-11ea-901c-9181c8245448.png)

**Comment by yuyutsupoudel** [comment]
Happens in both linux and windows.

**Comment by PerryHugh** [comment]
Confirmed.

**Comment by yuyutsupoudel** [comment]
[Video](https://streamable.com/qu0dgq)

**Comment by Zughy** [comment]
I guess this is related to Allegro 4? Possibly the SDL2 switch should fix it

**Comment by Zughy** [comment]
Duplicate of #87, which sounds more complete. Closing
