### ISSUE TITLE
LibreSprite v2 (Or whatever)

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/LibreSprite#75]
It's been almost a month since me and @PerryHugh got added to the LibreSprite team. To make this more known to people as a working project, and not a dead one, I think that a new release would be great. I'm not sure what version it should be, but here are the main three options:
 - v2
 - v1.1
 - v1.0.1
According to SemVer, option 3 would be correct. But for the good of LibreSprite (gaining more attention) the first option would be better. The question is, being correct, or gaining more attention?

I have created a new label, **cherry_pick**. Before our release, we should pick some doable features/issues, and have these assigned.

@maujin11 had an awesome idea, (Pixel Art Jam/Contest) more about it [here](http://www.libresprite.org/forums/viewtopic.php?f=9&t=7). I think that this would gain some new users, just like he said. I'm kind of iffy on a "free steam game" as recognition on the site should be enough. August 1st sounds like a nice date to me. We could take this to a monthly or bimonthly art jam.

After this is said and done, a post on the website should seal this (v2) up.

**Comment by jjhaggar** [comment]
I think being correct is better, but I understand your point. Maybe we could use the middle one as a compromise solution? I'm not sure about this.

The drawing contest is a great idea! :D

**Comment by MintStudios** [comment]
Well, it was all @maujin11!

**Comment by maujin111** [comment]
The idea of giving away a game comes from the need to motivate as many people as possible. Since it's the first Jam we're going to organize I think giving a prize would be good motivation. Carrion was released this week and got good reviews its an indie pixel art game. But any suggestions in good

**Comment by maujin111** [comment]
August 1st souds great. We have to have everything ready for that date or at least an attractive and user-friendly website.

**Comment by PerryHugh** [comment]
Our first release should probably be 1.0.

**Comment by maujin111** [comment]
Right now I am trying to compile for mac os but it is a headache. I'm not really familiar with Mac OS.

**Comment by yuyutsupoudel** [comment]
To get more users, there are pixel art related youtubers. I think we should ask some of them to create a review/free alternative to asprite type videos. If we even manage to get 5 10 youtubers, i think it will help a lot to get new users. Most of website still shows libresprite as discontinued alternative to asprite. Even website like [Alternativeto](https://alternativeto.net/software/libresprite/). I dont know how to contact them about it.

**Comment by jjhaggar** [comment]
I think we shouldn't rush the first release, if we delay the release date a bit it won't be a problem. The first impression is the most important one, so it's best if we are not in haste :)

Asking youtubers sounds great, but we should probably wait until first release is done (or have a confirmed date). Also, we should probably make a thread in [the forum](http://www.libresprite.org/forums/index.php) to suggest some Youtubers and maybe some other ways of letting people know about LibreSprite. Not sure in which part of the forum tho ^^U

About alternative.to, I've looked and when you try to suggest changes to an app, they say on the edit page:

> "Are you the developer/publisher of this application?
> Just send an e-mail with your username (from a e-mail connected to the company/organization) to hello@alternativeto.net and we will give you full access to edit your application so you can edit screenshots/icon and don't have to wait for approval. If you add a new item you will get full access to edit that."

Has anybody access to a libresprite.org email? If we write to them from one of these they'll give us full edit access.

**Comment by MintStudios** [comment]
Yes, I have email access. I might leave this to @PerryHugh because I'm not the best with words. But if he doesn't want to do it, I will.

**Comment by PerryHugh** [comment]
I'll get in touch. Meanwhile, these kinds of discussions are being migrated to the [forum](libresprite.org/forums/), so it is best not to open issues for them.
