### ISSUE TITLE
Homepage: Button is unresponsive 

### ISSUE THREAD

**Issue by ShalokShalom** [LibreSprite/LibreSprite#79]
The hamburger button on the top right at the mobile version is dead on my Firefox

https://libresprite.github.io/

**Comment by MintStudios** [comment]
Hello! The current LibreSprite website is at http://www.libresprite.org/

**Comment by ShalokShalom** [comment]
Well, then take this one down?

**Comment by PerryHugh** [comment]
I agree, the old one should be removed to aid confusion.

**Comment by ssokolow** [comment]
> Firefox can’t establish a connection to the server at www.libresprite.org

...but https://libresprite.github.io/ is still up and works perfectly fine for me. (So that's what I'll be linking people to.)

**Comment by jjhaggar** [comment]
> ...but https://libresprite.github.io/ is still up and works perfectly fine for me. (So that's what I'll be linking people to.)

Yeah, thanks! :) Right now the LibreSprite website is https://libresprite.github.io , the other one has been down for some months by now and we cannot contact the owner.

**Comment by maujin111** [comment]
The issue was fixed
