### ISSUE TITLE
When I execute the appImage file an empty folder named (invalid encoding) is created and the program does not launch.

### ISSUE THREAD

**Issue by This-Is-a-Username-lol** [LibreSprite/LibreSprite#84]
![Screenshot_2020-11-21_21-35-26](https://user-images.githubusercontent.com/72675527/99888361-2d0a9a80-2c44-11eb-9580-57ef3311b3a4.png)

OS: Debian GNU/Linux 10 (buster) i686

**Comment by maujin111** [comment]
It seems that the appimage is compiled for 64bits and that causes the error  @MintStudios  @PerryHugh

**Comment by MintStudios** [comment]
I believe so too. We would have to set up another build that would compile AppImages for i686.

**Comment by Zughy** [comment]
1.0 contains a 32 bit version too (https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0), closing

**Comment by mscharen** [comment]
I have had this general problem since I switched to Ubuntu. I've never had a single AppImage file run successfully. I'm running a 32 bit machine and the downloads often are not even labeled as 32 or 64 bit. Does this only happen when trying to run a 64 bit program on a 32 bit machine?

**Comment by This-Is-a-Username-lol** [comment]
@mscharen Appimages are often labeled with (x86_64) which means 64 bit while (x86) means 32 bit. 
Unfortunately 99% of AppImages out there are for 64 bit machines.
