### ISSUE TITLE
Grid lines not fully visible

### ISSUE THREAD

**Issue by haimat** [LibreSprite/LibreSprite#85]
Running LibreSprite on Windows 10 (installed via the official installer found here on GitHub) I have created a new 32x32 sprite and set the grid size to 32x32 as well. However, only two of the grid lines are visible, This can be seen in particular when the tiled mode is activated, as in the following screenshot:

![image](https://user-images.githubusercontent.com/6633976/100861824-a4d19400-3492-11eb-9f67-0febca08133b.png)

As you can see, the bottom and right grid/rectangle lines are not visible. Setting the grid to 31x31, i.e. one pixel less than the full sprite size, leads to the full grid rectangle visible, however, not in the correct size any more:

![image](https://user-images.githubusercontent.com/6633976/100861964-d3e80580-3492-11eb-823c-8d9501dcf2ed.png)

Is this a (known) bug, or am I missing somehting here?

**Comment by maujin111** [comment]
Hello, I imagine you want the grid to appear with 32x32 squares. You have to place in height and width 1 x 1
![grid](https://user-images.githubusercontent.com/25780951/100864672-4ab9da00-3464-11eb-820a-73b583a29a31.png)

**Comment by haimat** [comment]
> Hello @haimat, I imagine you want the grid to appear with 32x32 squares. 

No that is a misunderstanding. I do want a 32x32 grid, because I basically want to see the bounds/edges of my sprite when I use the tiled mode, as shown in my screenshots above.

**Comment by maujin111** [comment]
@haimat  
Sorry for my bad, I already reproduced what you are trying to do and only the lines appear on the x and y axis. And it only remains to say, it is not a bug, it is a feature! hahaha. Later tonight I will check the code to see if I can set the option to see all 4 sides

**Comment by haimat** [comment]
> 
> 
> @haimat
> Sorry for my bad, I already reproduced what you are trying to do and only the lines appear on the x and y axis. And it only remains to say, it is not a bug, it is a feature! hahaha. Later tonight I will check the code to see if I can set the option to see all 4 sides

Great, thanks for the clarification, @maujin111.
Is there any kind of workaround I can use until this is "fixed"?

**Comment by maujin111** [comment]
I was testing for a while and maybe if you work with a 33x33 cambas and make a 32x32 grid, the complete square is formed. Maybe you don't want to work that way but I can't think of another one at the moment, sorry @haimat, 
tonight I will do my best to solve that problem.

**Comment by haimat** [comment]
Well, if you can solve that in such a short time, then it's fine and I don't need a workaround.
Thanks a lot!

**Comment by haimat** [comment]
Hello @maujin111, have you had a chance to find a solution for this issue?

**Comment by maujin111** [comment]
Hi @haimat 
Yesterday I was playing around with the files a bit and I think I already have a solution, but I haven't had much time to test it. Today is my day off, I'll work on that.

**Comment by haimat** [comment]
The layer is a nice idea, thanks!

**Comment by haimat** [comment]
Hey @maujin111 - have you had any chance to look into this issue?
