### ISSUE TITLE
Is libresprite still active?

### ISSUE THREAD

**Issue by Midhil457** [LibreSprite/LibreSprite#86]
Hi, I have a doubt not a issue. Is libreaprite still worked on? As the last PR was 6 months ago. I am starting to learn coding and I would like to contribute to learn more! (Or atleast help decide features) Which language is it written in? Is this maintain by the same people who made libreoffice? Is this just a scam as the main site for it is full of redirect ads and the forum is full of bot comments. I know I should have asked this in the forum, but as I said it looked really inactive and full of junk and was afraid that I won't get an answer even after 5 years. 

Thanks for reading,
Bye

**Comment by MintStudios** [comment]
Yes, we are having some issues with the forum as there is a lot of spam. This project is the last open source fork of Aseprite, and @maujin111 is trying to get it working on a mac. Right now, there isn't a lot going on right now, but if you're learning to code, that's great! Aseprite and LibreSprite is built with c++. And no, we are not the people who made libreoffice. Anyways, it would be really great if you could contribute!

**Comment by maujin111** [comment]
hey @MintStudios i tried to reach you by your e-mail but i can't please contact me

**Comment by MintStudios** [comment]
I'll close this thread because LibreSprite is still in fact active, but just a little slow in development.

**Comment by Zughy** [comment]
(you forgot to close this)
