### ISSUE TITLE
Preview window fricking out when moved

### ISSUE THREAD

**Issue by Midhil457** [LibreSprite/LibreSprite#87]
Hi, Today I tried libresprite and immediately found a problem. The preview window started fricking out and made kind of the ghost version of it were ever I moved the mouse. But, it did not stop after stopping the mouse. The cursor started to flicker and and the software started lagging

![WHat?1](https://user-images.githubusercontent.com/73597906/103432718-71596500-4c0a-11eb-8a2c-64fdb76c6658.png)

![What?2](https://user-images.githubusercontent.com/73597906/103432721-728a9200-4c0a-11eb-8846-53e480480701.png)

**Comment by Midhil457** [comment]
And I forgot to say the software is really laggy

**Comment by maujin111** [comment]
Hello, thanks for let us know. I tried and yes the preview windows goes crazy, added to the bugs list, if you use the native cursor it gets better. For trying with the native cursor go to edit → preferences → Experimental and mark the "Use native mouse cursor" option. Also can you list your machine specifications to see in what hardware and software are you running libresprite

**Comment by Midhil457** [comment]
Sorry, I forgot to share the specs, Here it is:

OS :Linux Mint 20 x86_64
Kernal: 5.4.0-65-generic 
CPU: Pentium E5500 (2) @ 2.803GHz
GPU: Intel 4 Series Chipset 
Memory (RAM): 2GB

Yes, the system is a bit old, :sweat_smile:

**Comment by DarkoiV** [comment]
Hey, just wanted to report same issue, but not only with preview but also with pretty much any other secondary window. 
![libresprite](https://user-images.githubusercontent.com/25897608/108208598-855d1580-7129-11eb-92ba-42eda758046f.gif)

Also I don't think that native cursor changes this behavior that much. 
My specs:
OS: Ubuntu 20.04.2 LTS
Kernel: 5.4.0-65-generic
CPU: Intel i5-6200U (4) @ 2.800GHz
GPU: Intel Skylake GT2 [HD Graphics 520]
RAM: 8GB

**Comment by brickviking** [comment]
My specs:
OS: 64-bit Fedora Linux 28
Memory: 4GB
Kernel: linux-5.0.16
CPU: Core/2 Quad Q8400@2.66GHz
Video: ATI Radeon 3450, with 256MB video memory

I'm also noticing (especially for the preview window) the bug as of 2021-05-20 (1.0-dev, git version: 8a77f5a55213202a346e70088c4548b07afd5ed6)

It's definitely a bit annoying.

**Comment by felipemanga** [comment]
Is this still an issue?

**Comment by Midhil457** [comment]
Yes, The ghost thing  happens when you resize and move the preview window.
I got the AppImage from here: https://github.com/LibreSprite/LibreSprite/releases/tag/continuous
version 1.0-dev
Os: Linux Mint 20.2 Cinnamon

Here is a video:

https://user-images.githubusercontent.com/73597906/133960700-a7062f68-957e-4ff5-af81-35745ec87eae.mp4

**Comment by Zughy** [comment]
@Midhil457 that release still relies on Allegro4, you should test with the latest commits

**Comment by Midhil457** [comment]
Where are the nightly builds found?

**Comment by maujin111** [comment]
Fixed with the implement of sdl2 on the new pre-release https://github.com/LibreSprite/LibreSprite/releases/tag/v1.2.1-Beta

**Comment by Zughy** [comment]
That pre-release is not up to date with SDL2. Also, we have no proof SDL2 has fixed it

**Comment by maujin111** [comment]
I just uploaded the sdl2 version this morning, did you download the appimage and test it?

**Comment by Midhil457** [comment]
For some reason, the AppImage doesn't open, I extracted the zip, and for some reason, the `Allow executing` option was enabled automatically. ANd I can't open it. Nothing shows up, no processes are to be found in system processes

Is it a mistake on my side?
I tried,  https://github.com/LibreSprite/LibreSprite/releases/tag/v1.2.1-Beta and https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0-beta.1

**Comment by felipemanga** [comment]
Sounds like another case of dependecies not being bundled in the appimage.

**Comment by maujin111** [comment]
Anyone else is having this issue? @Zughy could you test it please

**Comment by maujin111** [comment]
i already updated the appimage, could anyone test it? 

https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0-beta.1

**Comment by maujin111** [comment]
here #228 we got confirmation that this bug is fixed
