### ISSUE TITLE
The libreSprite main page showing non-related stuff

### ISSUE THREAD

**Issue by Midhil457** [LibreSprite/LibreSprite#88]
Hi, so the main page of libresprite is full of non-related stuff and the bad thing is, the page is being edited frequently. You can see that the last edit was jan 1 2021. So, I think it is a bot that is doing this and this has to be stopped.

![Why?](https://user-images.githubusercontent.com/73597906/103432796-f1cc9580-4c0b-11eb-874b-4ab2c8db8122.png)

**Comment by maujin111** [comment]
I just reviewed it and I already corrected some things. I'm going to check security. Thanks for the warning. @MintStudios @PerryHugh  We are having some bots and security issues

**Comment by MintStudios** [comment]
@maujin111 and @PerryHugh , I think we should shut down the forums and/or wiki. Maujin111 thinks that the wiki is really not necessary, and I'm on board with that. The forums are spammed with russian text and really non-related things, such as help on java homework. Maybe to replace the forums, we could use github discussions, and I think @akien-mga might have to enable that. Github discussions have rolled out, and it might be better to have a forum type thing on github with the source and issues. What do you guys think?

**Comment by Midhil457** [comment]
> @maujin111 and @PerryHugh , I think we should shut down the forums and/or wiki. Maujin111 thinks that the wiki is really not necessary, and I'm on board with that. The forums are spammed with russian text and really non-related things, such as help on java homework. Maybe to replace the forums, we could use github discussions, and I think @akien-mga might have to enable that. Github discussions have rolled out, and it might be better to have a forum type thing on github with the source and issues. What do you guys think?

Just a suggestion, maybe move to github gradually like, not shut the forum down one day. Maybe like, when a new thread is made, show a notification to make them open that thread on github instead of the forum. And add the thread to make users know this forum will be shut down soon. And the wiki, maybe try to fix it and not shut it down as most people would look for a wiki first if they get a issue with the software and they will be doomed if the forum is also shut down

**Comment by MintStudios** [comment]
Well, if you already didn't know, the forum is probably confusing to newcomers because there are 10994 total members, and 722 total posts.

**Comment by neokeld** [comment]
http://libresprite.org/ seems to be down, so http://libresprite.org/wiki/index.php/Developer_Quick_Start is unreachable.

**Comment by MintStudios** [comment]
Aaah, I have no idea what's going on with the website
It was working temporarily for a bit.
https://libresprite.github.io is up - and the installation guide was deleted in the last PR.

However, you can access them here: https://github.com/LibreSprite/LibreSprite/commit/73f138ff13acdd85017e1f6d2ed44d4b9ff6dca3

You just have to load the diffs and you can see the deleted files.

Good thing about histories 👍

**Comment by Midhil457** [comment]
Now all the sites are reachable, by the way, I didn't know there was a libresprite.github.io site. The site looks really good

**Comment by maujin111** [comment]
I will link the docs (installation guide, etc) to [GitHub Page](https://libresprite.github.io ) as soon I can, but it will make a good idea to make a GitHub wiki and put the docs ther @MintStudios @PerryHugh @Calinou

**Comment by Luk3M** [comment]
Is the wiki available somewhere? The urls on the readme are unreachable. If you are considering changing the docs to somewhere else, maybe using [read the docs](https://readthedocs.org/) like Godot might be a good idea?

**Comment by Zughy** [comment]
@Luk3M Maujin is work on one, probably using the GitHub wiki feature. If you want to discuss the *read the docs* implementation, feel free to open an issue. Closing this one as the previous wiki doesn't exist anymore and this last topic is out of scope
