### ISSUE TITLE
Error when compiling on Debian Linux arm architecture

### ISSUE THREAD

**Issue by wanweiyang** [LibreSprite/LibreSprite#89]
I compile libresprite on Debian Linux arm architecture
There was a problem during compilation: https://pastebin.com/qwLj9NRv

Thank you for your reply

EDIT by Zughy: link instead of the veeery long log

**Comment by MintStudios** [comment]
Hello, one quick thing, could you put it somewhere like https://pastebin.com
It's a bit hard to read like this.

**Comment by wanweiyang** [comment]
I put it on that website, address: https://pastebin.com/qwLj9NRv

**Comment by wanweiyang** [comment]
I solved the problem of error reporting in curl. I git a new curl, but now I have a new compilation problem. FreeType2 reports an error. Can you help me：




[550/1006] Building C object third_party/freetype2/CMakeFiles/freetype.dir/src/gzip/ftgzip.c.o
FAILED: third_party/freetype2/CMakeFiles/freetype.dir/src/gzip/ftgzip.c.o 
/usr/bin/cc -DALLEGRO4_WITH_EXTRA_CURSORS -DALLEGRO4_WITH_RESIZE_PATCH -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_STATICLINK -DFT2_BUILD_LIBRARY -DNDEBUG -DPNG_NO_MMX_CODE -DUSE_ALLEG4_BACKEND -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/loadpng -I../third_party/curl/include -I../third_party/simpleini -I../src/allegro/include -Iinclude -I../third_party/. -I../third_party/gtest -I../third_party/gtest/include -Ithird_party/freetype2/include -I/usr/include/harfbuzz -g -O2 -fdebug-prefix-map=/home/uos/Desktop/aaa/lib/libresprite_uos=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -DNDEBUG -fvisibility=hidden -MD -MT third_party/freetype2/CMakeFiles/freetype.dir/src/gzip/ftgzip.c.o -MF third_party/freetype2/CMakeFiles/freetype.dir/src/gzip/ftgzip.c.o.d -o third_party/freetype2/CMakeFiles/freetype.dir/src/gzip/ftgzip.c.o   -c ../third_party/freetype2/src/gzip/ftgzip.c
In file included from ../third_party/freetype2/src/gzip/ftgzip.c:103:
../third_party/freetype2/src/gzip/inflate.c:30:8: error: redefinition of ‘struct internal_state’
 struct internal_state {
        ^~~~~~~~~~~~~~
In file included from ../third_party/freetype2/src/gzip/ftgzip.c:73:
../third_party/zlib/zlib.h:1742:12: note: originally defined here
     struct internal_state {int dummy;};
            ^~~~~~~~~~~~~~
In file included from ../third_party/freetype2/src/gzip/ftgzip.c:103:
../third_party/freetype2/src/gzip/inflate.c:54:9: error: expected identifier or ‘(’ before ‘int’
 ZEXPORT(int) inflateReset( /* z) */
         ^~~
../third_party/freetype2/src/gzip/inflate.c:68:9: error: expected identifier or ‘(’ before ‘int’
 ZEXPORT(int) inflateEnd( /* z) */
         ^~~
../third_party/freetype2/src/gzip/inflate.c:82:9: error: expected identifier or ‘(’ before ‘int’
 ZEXPORT(int) inflateInit2_( /* z, w, version, stream_size) */
         ^~~
../third_party/freetype2/src/gzip/inflate.c:147:9: error: expected identifier or ‘(’ before ‘int’
 ZEXPORT(int) inflate( /* z, f) */
         ^~~
In file included from ../third_party/freetype2/src/gzip/ftgzip.c:104:
../third_party/freetype2/src/gzip/adler32.c:21:9: error: expected identifier or ‘(’ before ‘uLong’
 ZEXPORT(uLong) adler32( /* adler, buf, len) */
         ^~~~~
[555/1006] Building CXX object src/ui/CMakeFiles/ui-lib.dir/widget.cpp.o
../src/ui/widget.cpp: In member function ‘virtual bool ui::Widget::onProcessMessage(ui::Message*)’:
../src/ui/widget.cpp:1327:28: warning: enum constant in boolean context [-Wint-in-bool-context]
       if (kMouseDownMessage) {
                            ^
[566/1006] Building C object src/script/CMakeFiles/duktape.dir/__/__/third_party/duktape/duktape.c.o
../third_party/duktape/duktape.c: In function ‘duk__format_parts_iso8601’:
../third_party/duktape/duktape.c:28576:46: warning: ‘%02d’ directive output may be truncated writing 2 bytes into a region of size between 0 and 4 [-Wformat-truncation=]
    DUK_SNPRINTF(tzstr, sizeof(tzstr), "-%02d:%02d", (int) (tmp / 60), (int) (tmp % 60));
                                              ^~~~
../third_party/duktape/duktape.c:28576:39: note: directive argument in the range [0, 59]
    DUK_SNPRINTF(tzstr, sizeof(tzstr), "-%02d:%02d", (int) (tmp / 60), (int) (tmp % 60));
                                       ^~~~~~~~~~~~
In file included from ../third_party/duktape/duktape.h:126,
                 from ../third_party/duktape/duktape.c:136:
../third_party/duktape/duk_config.h:1925:26: note: ‘snprintf’ output between 7 and 11 bytes into a destination of size 8
 #define DUK_SNPRINTF     snprintf
../third_party/duktape/duktape.c:28576:4: note: in expansion of macro ‘DUK_SNPRINTF’
    DUK_SNPRINTF(tzstr, sizeof(tzstr), "-%02d:%02d", (int) (tmp / 60), (int) (tmp % 60));
    ^~~~~~~~~~~~
../third_party/duktape/duktape.c:28573:46: warning: ‘%02d’ directive output may be truncated writing 2 bytes into a region of size between 0 and 4 [-Wformat-truncation=]
    DUK_SNPRINTF(tzstr, sizeof(tzstr), "+%02d:%02d", (int) (tmp / 60), (int) (tmp % 60));
                                              ^~~~
../third_party/duktape/duktape.c:28573:39: note: directive argument in the range [0, 59]
    DUK_SNPRINTF(tzstr, sizeof(tzstr), "+%02d:%02d", (int) (tmp / 60), (int) (tmp % 60));
                                       ^~~~~~~~~~~~
In file included from ../third_party/duktape/duktape.h:126,
                 from ../third_party/duktape/duktape.c:136:
../third_party/duktape/duk_config.h:1925:26: note: ‘snprintf’ output between 7 and 11 bytes into a destination of size 8
 #define DUK_SNPRINTF     snprintf
../third_party/duktape/duktape.c:28573:4: note: in expansion of macro ‘DUK_SNPRINTF’
    DUK_SNPRINTF(tzstr, sizeof(tzstr), "+%02d:%02d", (int) (tmp / 60), (int) (tmp % 60));
    ^~~~~~~~~~~~

**Comment by jpellegrini** [comment]
Hello @wanweiyang 

> I solved the problem of error reporting in curl. I git a new curl

How did you do that?
Are you running raspbian?

On Raspbian stable and Raspbian testing I also get the error you've reported with the latest shipped libcurl (libcurl4-dev)

**Comment by VirtualOverrider** [comment]
Installing **libcurl4-openssl-dev** resolved the curl errors for me. Then **libsdl2-dev** and **libsdl2-image-dev** for the sdl_image issue which presented afterwards.

**Comment by Zughy** [comment]
@VirtualOverrider can you please try with `libcurl4-gnutls-dev` instead? We're not using openSSL because it conflicts with the GPL license (info [here](https://askubuntu.com/questions/78183/installing-curl-h-library#) and [here](https://people.gnome.org/~markmc/openssl-and-the-gpl.html))

**Comment by VirtualOverrider** [comment]
> @VirtualOverrider can you please try with `libcurl4-gnutls-dev` instead? We're not using openSSL because it conflicts with the GPL license (info [here](https://askubuntu.com/questions/78183/installing-curl-h-library#) and [here](https://people.gnome.org/~markmc/openssl-and-the-gpl.html))

Can confirm compiles and runs fine with `libcurl4-gnutls-dev`. Good catch on the licensing, didn't even cross my mind.

**Comment by Zughy** [comment]
Thanks for testing! Closing, hoping it's fixed for everyone
