### ISSUE TITLE
More preloaded palettes and a search bar for them 

### ISSUE THREAD

**Issue by pepsiux11** [LibreSprite/LibreSprite#93]
It is basicly the same as the title, but I would love to see this. If I as a programmer would take my time at learning c++ would maybe contribute to the project. I love libreSprite and now asI  started to use it for piexl art I wanted to give some ideas to you developers. This is not an isue, but more a request.

**Comment by maujin111** [comment]
That is fantastic, more help is always welcome, and it's much better if it is from a developer who is also a pixel artist. We look forward to your ideas and contributions

**Comment by maujin111** [comment]
Continue the discussion on #130
