### ISSUE TITLE
Differences with aseprite?

### ISSUE THREAD

**Issue by ramirez7** [LibreSprite/LibreSprite#94]
Since this is a fork from 2016, I'd imagine aseprite has a bunch of features LibreSprite doesn't. Is there any documentation of this? And for any missing features, are there plans to get parity?

On the flip side, are there LibreSprite features aseprite doesn't have?

Glad to see a GPL fork is alive and well!

**Comment by maujin111** [comment]
LibreSprite maintains the philosophy of open source code, and to be honest and straightforward the answer is "yes" LibreSprite lacks some features that the other software mentioned has and has some bugs that are already resolved in the other software. But we are working hard to get this project out, in our spare time trying to fix the bugs, devise new features and little by little improve and make LibreSprite recognized for being its own software and not another fork. For that we need help, if you are willing to help please read the guides on how to contribute or use the software and report bugs. Thank you

**Comment by ramirez7** [comment]
> For that we need help, if you are willing to help please read the guides on how to contribute or use the software and report bugs.

I'll give it a try! I've used aseprite but given the success and quality of Blender and Krita, I definitely would prefer a proper open source option.

I run NixOS, so I'll package it up for myself first, and then upstream the packaging to `nixpkgs` for everyone 🤘

**Comment by maujin111** [comment]
> I run NixOS, so I'll package it up for myself first, and then upstream the packaging to nixpkgs for everyone 🤘

That's amazing thanks, but I try to find the package in nixpkgs repositories but is no there, maybe you can send me a link or instructions about to how to install the package on NixOS to put it on the webpage

**Comment by maujin111** [comment]
@MintStudios please close the issue
