### ISSUE TITLE
Hardware acceleration on Windows 10?

### ISSUE THREAD

**Issue by K1NGM4RV** [LibreSprite/LibreSprite#95]
The mouse is laggy when I move over the canvas with it. Is there a simple way to fix it? No pressure, it's not of high priority ^^
Thanks for this amazing fork! Take care!

**Comment by maujin111** [comment]
Are you trying the configuration: Edit → Preferences → Experimental and mark the option "Use native Mouse Cursor" then click to apply 

![image](https://user-images.githubusercontent.com/25780951/107459182-999a8480-6b23-11eb-90a3-594f5a70f108.png)

**Comment by K1NGM4RV** [comment]
Oh wow that indeed fixed the issue. Thank you very much @maujin111!

**Comment by maujin111** [comment]
We are here to help, Thanks to you for the feedback

**Comment by MintStudios** [comment]
I guess with that we can close the issue.
