### ISSUE TITLE
Grid size can't be 1x1?

### ISSUE THREAD

**Issue by nullbasis** [LibreSprite/LibreSprite#96]
1x1 seems like the most obvious grid size to have available when working with tiny sprites (on the order of 8 or 16px) but it's not even an option. Can this be added?

**Comment by MintStudios** [comment]
Hmm, 1x1. What's your use case for this? To me, it just sounds like a single colored square. Or do you mean working in half or quarter sprites?

**Comment by nullbasis** [comment]
To me, having a 2x2 grid when I'm working like this is really weird:

![Screenshot-20210213141550-1233x983](https://user-images.githubusercontent.com/13566767/107860658-5a787600-6e38-11eb-849c-d85ace23a956.png)

For contrast, I usually work in GIMP or Glimpse and have the grid option set to one pixel, like so:

![Screenshot-20210213142032-835x790](https://user-images.githubusercontent.com/13566767/107860763-0fab2e00-6e39-11eb-8cf4-9f095a82757c.png)

(But I much prefer LibreSprite for spritework, aside from this one issue.)

**Comment by KikooDX** [comment]
Hello, you can enable Pixel Grid (View → Show → Pixel Grid) to achieve the effect you are looking for, it is even possible to enable the Grid on top of it.
![image](https://user-images.githubusercontent.com/30863886/109141432-03d73a00-775e-11eb-9822-3366a2f5fe06.png)
Hope this solve your issue.

**Comment by nullbasis** [comment]
So, the same as the grid in Glimpse? Not my favorite solution, but it'll do. Thanks.
