### ISSUE TITLE
when i launch it says File skins/Pirobit/sheet.png not found

### ISSUE THREAD

**Issue by Pirobit** [LibreSprite/LibreSprite#98]
I tried to use a theme from aseprite, I renamed it btw and now I cant launch libresprite
I had tried to uninstall it several times but that didn't work

**Comment by maujin111** [comment]
Sorry for the late reply, are you using Linux or windows?

**Comment by Pirobit** [comment]
I am using windows 10
but I already fixed the problem
I just copied the default theme into my theme
I'm pretty sure aseprite themes don't work

**Comment by maujin111** [comment]
To use those themes you have to do some tweaks to the theme files. Check out the than-dark-theme on my repo.
