### ISSUE TITLE
File skin/Aseprite Wild Night Theme/sheet png not found

### ISSUE THREAD

**Issue by NonnaCafe** [LibreSprite/LibreSprite#99]

**Comment by maujin111** [comment]
To use themes that are not adapted for LibreSprite you have to make modifications to the XML theme file. Please send the theme link to modify the files, or you can use [this](https://github.com/maujin111/than_dark_theme_libresprite) theme as a reference.

**Comment by NonnaCafe** [comment]
https://wildleoknight.itch.io/aseprite-wild-night-theme           the orange one

**Comment by maujin111** [comment]
I still have to work on some colors of the theme but it is already functional, this is the [repository](https://github.com/maujin111/wild-night-theme-orange) . when I have time I will continue adapting it 

![Captura de pantalla 2021-03-03 082955](https://user-images.githubusercontent.com/25780951/109812934-ae39dc00-7bfa-11eb-9772-71efeb88433e.png)

**Comment by NonnaCafe** [comment]
i put the file inside the skins file and it still wont open

**Comment by maujin111** [comment]
Have you followed the instructions on the README file?

**Comment by maujin111** [comment]
You have to download the zip and extract it on the Skins folder

**Comment by NonnaCafe** [comment]
![image](https://user-images.githubusercontent.com/76004804/109832080-b587d680-7c48-11eb-86a1-a605fcd259a2.png)

**Comment by NonnaCafe** [comment]
like that?

**Comment by maujin111** [comment]
Yes, is still not working?

**Comment by NonnaCafe** [comment]
its not i launch
 the software and its shows that theres a error

**Comment by NonnaCafe** [comment]
it used to work fine (few months ago) but when i changed it in libresprite (not the files) but when i changed it stopped working

**Comment by maujin111** [comment]
That's weird I tried it on Linux and windows and works, have you tried to uninstall and install again?

**Comment by NonnaCafe** [comment]
multiple times

**Comment by maujin111** [comment]
Have you tried to delete the folder "LibreSprite" on "AppData\Roaming\LibreSprite" and Install again?

**Comment by NonnaCafe** [comment]
i fixed it, i opened the configuration setting file in here AppData\Roaming\LibreSprite and change the the to default

**Comment by maujin111** [comment]
Great, later today I will continue fixing some color issues to make it more appealing

**Comment by NonnaCafe** [comment]
thanks
